<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\EventHastana;
use App\Models\EventCategory;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class EventHastanaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ambil semua kategori
        $categories = EventCategory::all();
        
        if ($categories->isEmpty()) {
            $this->command->warn('Event categories tidak ditemukan. Jalankan EventCategorySeeder terlebih dahulu.');
            return;
        }

        $allEvents = [];

        // ============================================
        // KATEGORI 1: WORKSHOP & PELATIHAN (5 events)
        // ============================================
        $workshopCategory = $categories->where('slug', 'workshop-pelatihan')->first();
        if ($workshopCategory) {
            $allEvents = array_merge($allEvents, [
                [
                    'title' => 'Workshop Digital Marketing & Social Media Strategy 2025',
                    'slug' => 'workshop-digital-marketing-social-media-strategy-2025',
                    'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'location_type' => 'offline',
                    'online_link' => null,
                    'description' => '<p>Workshop intensif 2 hari tentang strategi digital marketing terkini untuk meningkatkan brand awareness dan penjualan bisnis Anda.</p><p><strong>Materi yang akan dibahas:</strong></p><ul><li>Social Media Marketing Strategy (Instagram, TikTok, LinkedIn)</li><li>Content Marketing & SEO Optimization</li><li>Facebook & Instagram Ads</li><li>Google Ads & Analytics</li><li>Email Marketing Automation</li><li>Influencer Marketing</li></ul><p><strong>Instruktur:</strong> Tim praktisi digital marketing dengan pengalaman 10+ tahun di berbagai industri</p>',
                    'short_description' => 'Workshop intensif strategi digital marketing untuk meningkatkan brand awareness dan penjualan bisnis.',
                    'start_date' => '2025-11-15',
                    'end_date' => '2025-11-16',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Jl. Gatot Subroto Kav. 52-53, Jakarta Selatan 12950',
                    'venue' => 'Jakarta Convention Center - Ruang Seminar A, Lantai 3',
                    'city' => 'Jakarta Selatan',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 500000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Dengan mengikuti workshop ini, Anda akan mendapatkan berbagai keuntungan berikut:</p><ol><li>E-Certificate yang dapat digunakan untuk portofolio profesional</li><li>Lunch dan Coffee Break selama 2 hari workshop</li><li>Modul Digital Marketing lengkap dalam format PDF</li><li>Template Campaign siap pakai untuk berbagai platform</li><li>Free konsultasi personal selama 1 bulan setelah workshop</li><li>Akses ke komunitas Digital Marketer eksklusif untuk networking</li></ol>',
                    'requirements' => '• Membawa laptop\n• Email aktif untuk akses materi\n• Memiliki akun social media\n• Basic knowledge tentang bisnis',
                    'organizer_name' => 'HASTANA Indonesia',
                    'contact_email' => 'workshop@hastanaindonesia.com',
                    'contact_phone' => '+62 812-3456-7890',
                    'tags' => json_encode(['digital-marketing', 'workshop', 'business', 'social-media', 'seo', 'advertising']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                    'rating' => 4.8,
                    'total_reviews' => 42,
                ],
                [
                    'title' => 'Workshop Content Creation: Fotografi & Videografi untuk Bisnis',
                    'slug' => 'workshop-content-creation-fotografi-videografi-bisnis',
                    'image' => 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'location_type' => 'hybrid',
                    'online_link' => 'https://zoom.us/j/987654321?pwd=abcdef123',
                    'description' => '<p>Workshop praktis membuat konten visual menarik untuk meningkatkan engagement di social media bisnis Anda.</p><p><strong>Materi meliputi:</strong></p><ul><li>Dasar Fotografi Produk</li><li>Teknik Lighting & Komposisi</li><li>Video Marketing untuk Instagram Reels & TikTok</li><li>Mobile Photography & Editing</li><li>Copywriting untuk Visual Content</li><li>Planning & Scheduling Content</li></ul><p><strong>Format Hybrid:</strong> Peserta dapat mengikuti secara offline di studio atau online via Zoom</p>',
                    'short_description' => 'Workshop praktis fotografi dan videografi untuk konten bisnis yang engaging.',
                    'start_date' => '2025-12-08',
                    'end_date' => '2025-12-08',
                    'start_time' => '09:00:00',
                    'end_time' => '16:00:00',
                    'location' => 'Jl. Kemang Raya No. 12A, Jakarta Selatan 12560',
                    'venue' => 'HASTANA Creative Studio - Studio Room & Meeting Room 1',
                    'city' => 'Jakarta Selatan',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 350000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Peserta workshop akan memperoleh manfaat maksimal melalui:</p><ol><li>E-Certificate resmi sebagai bukti keikutsertaan workshop</li><li>Lunch dan Coffee Break untuk networking dengan sesama peserta</li><li>Modul Content Creation komprehensif untuk dipelajari di rumah</li><li>Template Design Pack berisi 50+ template siap pakai</li><li>Preset Editing Lightroom dan VSCO untuk hasil foto profesional</li><li>Recording session khusus untuk peserta online yang dapat diakses kapan saja</li></ol>',
                    'requirements' => '• Smartphone dengan kamera bagus atau kamera DSLR/Mirrorless\n• Laptop (optional untuk editing)\n• Tripod kecil (disarankan)\n• Untuk peserta online: koneksi internet stabil',
                    'organizer_name' => 'HASTANA Creative Studio',
                    'contact_email' => 'creative@hastanaindonesia.com',
                    'contact_phone' => '+62 812-3456-7891',
                    'tags' => json_encode(['content-creation', 'workshop', 'fotografi', 'videografi', 'social-media', 'hybrid']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                    'rating' => 4.6,
                    'total_reviews' => 28,
                ],
                [
                    'title' => 'Pelatihan Microsoft Excel Advanced untuk Profesional',
                    'slug' => 'pelatihan-microsoft-excel-advanced-profesional',
                    'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'internal',
                    'location_type' => 'offline',
                    'online_link' => null,
                    'description' => '<p>Pelatihan intensif Microsoft Excel tingkat lanjut untuk meningkatkan produktivitas kerja dan analisis data.</p><p><strong>Materi yang dipelajari:</strong></p><ul><li>Advanced Formula & Functions (VLOOKUP, INDEX-MATCH, XLOOKUP)</li><li>Pivot Tables & Advanced Charts</li><li>Data Analysis & Visualization Techniques</li><li>Macro & VBA Automation untuk efisiensi</li><li>Dashboard Creation yang interaktif</li><li>Power Query & Power Pivot untuk Big Data</li><li>Financial Modeling & Forecasting</li></ul><p><strong>Target:</strong> Profesional yang ingin meningkatkan skill Excel untuk analisis data dan reporting</p>',
                    'short_description' => 'Pelatihan Excel tingkat lanjut untuk meningkatkan produktivitas kerja dan analisis data profesional.',
                    'start_date' => '2025-11-25',
                    'end_date' => '2025-11-26',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Jl. Sudirman Kav. 25, Jakarta Pusat 10270',
                    'venue' => 'HASTANA Training Center - Lab Komputer 1',
                    'city' => 'Jakarta Pusat',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 750000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Investasi terbaik untuk meningkatkan skill Excel Anda dengan mendapatkan:</p><ol><li>Sertifikat Resmi Microsoft Partner yang diakui secara internasional</li><li>Lunch dan Coffee Break selama 2 hari pelatihan</li><li>Modul Excel Advanced dalam format PDF untuk referensi selamanya</li><li>File latihan dan template Excel yang dapat langsung digunakan di pekerjaan</li><li>Free update materi selamanya ketika ada versi Excel terbaru</li><li>Akses grup alumni untuk diskusi dan sharing knowledge berkelanjutan</li></ol>',
                    'requirements' => '• Laptop dengan MS Excel 2016 atau lebih baru\n• Dasar Excel (formula sederhana, formatting)\n• Pengalaman kerja dengan data minimal 1 tahun\n• Mouse (sangat disarankan)',
                    'organizer_name' => 'HASTANA Training Center',
                    'contact_email' => 'training@hastanaindonesia.com',
                    'contact_phone' => '+62 812-3456-7892',
                    'tags' => json_encode(['excel', 'workshop', 'productivity', 'data-analysis', 'microsoft-office', 'professional']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => false,
                    'rating' => 4.9,
                    'total_reviews' => 35,
                ],
                [
                    'title' => 'Workshop Graphic Design dengan Adobe Photoshop & Illustrator',
                    'slug' => 'workshop-graphic-design-adobe-photoshop-illustrator',
                    'image' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'location_type' => 'offline',
                    'online_link' => null,
                    'description' => '<p>Workshop praktis desain grafis menggunakan Adobe Photoshop dan Illustrator untuk pemula hingga menengah.</p><p><strong>Yang akan dipelajari:</strong></p><ul><li>Fundamental Design Principles</li><li>Adobe Photoshop: Photo Editing & Manipulation</li><li>Adobe Illustrator: Vector Design & Logo Creation</li><li>Typography & Color Theory</li><li>Social Media Design Assets</li><li>Portfolio Creation</li></ul><p><strong>Target:</strong> Pemula hingga menengah yang ingin menguasai design tools</p>',
                    'short_description' => 'Workshop desain grafis dengan Photoshop & Illustrator untuk pemula hingga menengah.',
                    'start_date' => '2025-12-15',
                    'end_date' => '2025-12-15',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Jl. Dago No. 56, Bandung 40135',
                    'venue' => 'HASTANA Design Studio - Creative Space',
                    'city' => 'Bandung',
                    'province' => 'Jawa Barat',
                    'is_free' => false,
                    'price' => 450000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Workshop ini memberikan value luar biasa untuk journey desain Anda:</p><ol><li>E-Certificate yang dapat memperkuat portofolio dan CV Anda</li><li>Lunch dan Coffee Break untuk networking dengan designer lainnya</li><li>Modul Design lengkap mencakup teori dan praktik desain modern</li><li>Template dan Mockup Pack berisi 500+ assets premium siap pakai</li><li>Free konsultasi portfolio untuk membantu mengembangkan karya terbaik Anda</li><li>Akses grup alumni designer untuk kolaborasi dan job opportunities</li></ol>',
                    'requirements' => '• Laptop dengan Adobe Photoshop & Illustrator terinstall\n• Mouse (sangat disarankan)\n• Basic computer knowledge\n• Membawa charger laptop',
                    'organizer_name' => 'HASTANA Creative Academy',
                    'contact_email' => 'creative@hastanaindonesia.com',
                    'contact_phone' => '+62 812-3456-7895',
                    'tags' => json_encode(['graphic-design', 'workshop', 'photoshop', 'illustrator', 'design', 'creative']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                    'rating' => 4.7,
                    'total_reviews' => 38,
                ],
                [
                    'title' => 'Workshop Public Speaking & Presentation Skills',
                    'slug' => 'workshop-public-speaking-presentation-skills',
                    'image' => 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'location_type' => 'offline',
                    'online_link' => null,
                    'description' => '<p>Workshop praktis untuk meningkatkan kemampuan berbicara di depan umum dan presentasi yang memukau.</p><p><strong>Materi yang dipelajari:</strong></p><ul><li>Overcoming Stage Fright & Building Confidence</li><li>Body Language & Voice Control</li><li>Storytelling Techniques yang engaging</li><li>Slide Design yang Efektif dan menarik</li><li>Q&A Handling dengan percaya diri</li><li>Impromptu Speaking skills</li><li>Virtual Presentation untuk era digital</li></ul><p><strong>Metode:</strong> 70% praktek, 30% teori dengan video analysis</p>',
                    'short_description' => 'Workshop praktis untuk meningkatkan kemampuan public speaking dan presentasi yang memukau.',
                    'start_date' => '2025-12-22',
                    'end_date' => '2025-12-22',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Jl. Pemuda No. 123, Surabaya 60271',
                    'venue' => 'Grand Event Hall Surabaya - Main Hall',
                    'city' => 'Surabaya',
                    'province' => 'Jawa Timur',
                    'is_free' => false,
                    'price' => 400000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Transformasi kemampuan public speaking Anda melalui:</p><ol><li>E-Certificate yang membuktikan kompetensi public speaking Anda</li><li>Lunch dan Coffee Break untuk praktik networking dalam suasana santai</li><li>Modul Public Speaking komprehensif dengan tips dan teknik terbukti</li><li>Video rekaman presentasi personal untuk evaluasi dan perbaikan diri</li><li>1 bulan mentoring online dengan expert untuk pengembangan berkelanjutan</li><li>Template presentasi profesional yang dapat digunakan untuk berbagai keperluan</li></ol>',
                    'requirements' => '• Tidak ada requirement khusus, cocok untuk pemula\n• Membawa notebook untuk catatan\n• Smartphone untuk video practice',
                    'organizer_name' => 'HASTANA Communication Institute',
                    'contact_email' => 'communication@hastanaindonesia.com',
                    'contact_phone' => '+62 812-3456-7893',
                    'tags' => json_encode(['public-speaking', 'workshop', 'communication', 'soft-skills', 'presentation']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                    'rating' => 4.7,
                    'total_reviews' => 31,
                ],
                [
                    'title' => 'Webinar: Future of Digital Business & AI Implementation',
                    'slug' => 'webinar-future-digital-business-ai-implementation',
                    'image' => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'location_type' => 'online',
                    'online_link' => 'https://zoom.us/j/123456789?pwd=webinar2025',
                    'description' => '<p>Webinar eksklusif membahas masa depan bisnis digital dan implementasi AI untuk meningkatkan efisiensi bisnis.</p><p><strong>Topik Bahasan:</strong></p><ul><li>Tren Digital Business 2025-2030</li><li>AI Tools untuk Automation bisnis</li><li>ChatGPT & AI untuk Marketing</li><li>Data Analytics dengan AI</li><li>Customer Service Automation</li><li>ROI Implementation AI in Business</li><li>Case Study: Successful AI Implementation</li></ul><p><strong>Bonus:</strong> Recording webinar + AI Tools List + Templates</p>',
                    'short_description' => 'Webinar eksklusif tentang masa depan bisnis digital dan implementasi AI untuk efisiensi bisnis.',
                    'start_date' => '2025-11-20',
                    'end_date' => '2025-11-20',
                    'start_time' => '19:00:00',
                    'end_time' => '21:00:00',
                    'location' => 'Online via Zoom Meeting',
                    'venue' => 'Virtual Event Platform',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => true,
                    'price' => 0,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Webinar eksklusif membahas masa depan bisnis digital dan implementasi AI untuk meningkatkan efisiensi bisnis.</p><ol><li>E-Certificate of Attendance untuk menambah kredibilitas profesional Anda</li><li>Recording webinar dengan akses 7 hari untuk dapat dipelajari berulang kali</li><li>AI Tools Checklist berisi daftar tools AI terbaik untuk berbagai kebutuhan bisnis</li><li>Business AI Implementation Template untuk memulai implementasi AI di perusahaan</li><li>Q&A session langsung dengan expert AI dan digital business</li><li>Early bird access untuk workshop lanjutan dengan diskon khusus</li></ol>',
                    'requirements' => '• Koneksi internet stabil\n• Laptop/smartphone untuk akses Zoom\n• Basic knowledge tentang bisnis digital (optional)',
                    'organizer_name' => 'HASTANA Digital Institute',
                    'contact_email' => 'webinar@hastanaindonesia.com',
                    'contact_phone' => '+62 812-3456-7894',
                    'tags' => json_encode(['webinar', 'ai', 'digital-business', 'automation', 'future-tech', 'online']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                    'rating' => 4.5,
                    'total_reviews' => 156,
                ],
            ]);
        }

        // ============================================
        // KATEGORI 2: SEMINAR & TALKSHOW (5 events)
        // ============================================
        $seminarCategory = $categories->where('slug', 'seminar-talkshow')->first();
        if ($seminarCategory) {
            $allEvents = array_merge($allEvents, [
                [
                    'title' => 'Seminar Kewirausahaan: From Zero to Hero',
                    'slug' => 'seminar-kewirausahaan-from-zero-to-hero',
                    'image' => 'https://images.unsplash.com/photo-1556761175-b413da4baf72?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Seminar inspiratif bersama para entrepreneur sukses yang memulai bisnis dari nol hingga mencapai kesuksesan luar biasa.</p><p><strong>Pembicara:</strong></p><ul><li>Budi Santoso - Founder Tech Startup Unicorn (Valuasi $1B+)</li><li>Siti Nurhaliza - CEO E-Commerce Fashion Terbesar</li><li>Ahmad Dhani - Owner 100+ Franchise F&B di Indonesia</li><li>Linda Wijaya - Social Media Influencer & Business Owner</li></ul><p>Dapatkan insight langsung dari perjalanan mereka membangun bisnis dari nol!</p>',
                    'short_description' => 'Seminar inspiratif bersama entrepreneur sukses yang memulai bisnis dari nol hingga sukses.',
                    'start_date' => '2025-12-05',
                    'end_date' => '2025-12-05',
                    'start_time' => '13:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Ballroom Hotel Santika',
                    'venue' => 'Grand Ballroom',
                    'city' => 'Bandung',
                    'province' => 'Jawa Barat',
                    'is_free' => false,
                    'price' => 250000,
                    'quota' => 200,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Seminar inspiratif ini memberikan value luar biasa untuk perjalanan wirausaha Anda:</p><ol><li>E-Certificate resmi sebagai bukti keikutsertaan seminar kewirausahaan</li><li>Snack dan refreshment berkualitas selama acara berlangsung</li><li>Networking session eksklusif dengan entrepreneur sukses dan sesama peserta</li><li>Business Plan Template siap pakai untuk memulai bisnis impian Anda</li><li>Doorprize menarik termasuk buku bisnis dan voucher konsultasi</li><li>Akses recording seminar untuk dapat dipelajari berulang kali</li></ol>',
                    'requirements' => 'Minat di bidang wirausaha, Membawa kartu identitas',
                    'organizer_name' => 'HASTANA Indonesia x Komunitas Wirausaha Muda',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567894',
                    'tags' => json_encode(['entrepreneurship', 'seminar', 'business', 'startup', 'inspirasi']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Talkshow: Future of Technology & Innovation 2025',
                    'slug' => 'talkshow-future-technology-innovation-2025',
                    'image' => 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Talkshow eksklusif membahas tren teknologi terkini dan masa depan inovasi digital.</p><p><strong>Topik Diskusi:</strong></p><ul><li>Artificial Intelligence & Machine Learning</li><li>Blockchain & Web3</li><li>Internet of Things (IoT)</li><li>Metaverse & Virtual Reality</li><li>Sustainable Technology</li></ul><p><strong>Narasumber:</strong> Tech Leaders dari Google, Microsoft, dan Startup Indonesia</p>',
                    'short_description' => 'Talkshow tentang tren teknologi dan inovasi digital masa depan.',
                    'start_date' => '2025-11-22',
                    'end_date' => '2025-11-22',
                    'start_time' => '14:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Auditorium Universitas Indonesia',
                    'venue' => 'Auditorium Utama',
                    'city' => 'Depok',
                    'province' => 'Jawa Barat',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 300,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Talkshow teknologi yang memberikan insight valuable untuk masa depan Anda:</p><ol><li>E-Certificate keikutsertaan talkshow teknologi dan inovasi</li><li>Snack dan refreshment premium selama acara</li><li>Networking session dengan tech leaders dan praktisi industri</li><li>Akses materi PDF berisi slide presentasi dan resource tambahan</li><li>Doorprize gadget menarik dari sponsor teknologi terkemuka</li><li>Kesempatan Q&A langsung dengan narasumber expert</li></ol>',
                    'requirements' => 'Registrasi online, Mahasiswa/Umum dipersilakan',
                    'organizer_name' => 'HASTANA Indonesia x UI Computer Science',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567895',
                    'tags' => json_encode(['technology', 'talkshow', 'innovation', 'ai', 'free-event']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Seminar Kesehatan Mental di Tempat Kerja',
                    'slug' => 'seminar-kesehatan-mental-tempat-kerja',
                    'image' => 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Seminar penting tentang menjaga kesehatan mental di lingkungan kerja yang dinamis dan penuh tekanan.</p><p><strong>Materi:</strong></p><ul><li>Mengenali Tanda-tanda Burnout</li><li>Stress Management Techniques</li><li>Work-Life Balance</li><li>Building Resilience</li><li>Mental Health First Aid</li></ul><p><strong>Pembicara:</strong> Psikolog Klinis dan HR Professionals</p>',
                    'short_description' => 'Seminar tentang menjaga kesehatan mental di lingkungan kerja.',
                    'start_date' => '2025-11-28',
                    'end_date' => '2025-11-28',
                    'start_time' => '14:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Auditorium Universitas Gadjah Mada',
                    'venue' => 'Auditorium Psikologi',
                    'city' => 'Yogyakarta',
                    'province' => 'DI Yogyakarta',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 250,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Seminar kesehatan mental yang memberikan dukungan komprehensif:</p><ol><li>E-Certificate keikutsertaan seminar kesehatan mental di tempat kerja</li><li>Snack sehat dan minuman yang mendukung wellbeing</li><li>Konseling gratis 1 kali dengan psikolog profesional setelah seminar</li><li>Modul Mental Health lengkap untuk dipraktikkan di kehidupan sehari-hari</li><li>Relaksasi session guided meditation untuk mengurangi stress</li><li>Assessment kesehatan mental sederhana untuk self-awareness</li></ol>',
                    'requirements' => 'Registrasi online, Terbuka untuk umum',
                    'organizer_name' => 'HASTANA Indonesia x UGM Psychology',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567896',
                    'tags' => json_encode(['mental-health', 'seminar', 'workplace', 'free-event', 'wellbeing']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Talkshow Financial Planning untuk Generasi Milenial & Gen Z',
                    'slug' => 'talkshow-financial-planning-milenial-gen-z',
                    'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Talkshow interaktif tentang perencanaan keuangan untuk generasi muda.</p><p><strong>Topik:</strong></p><ul><li>Budgeting & Saving Tips</li><li>Investasi untuk Pemula</li><li>Passive Income Strategy</li><li>Crypto & Digital Assets</li><li>Retirement Planning di Usia Muda</li></ul><p><strong>Pembicara:</strong> Certified Financial Planner & Successful Young Investor</p>',
                    'short_description' => 'Talkshow financial planning untuk generasi milenial dan Gen Z.',
                    'start_date' => '2025-12-12',
                    'end_date' => '2025-12-12',
                    'start_time' => '19:00:00',
                    'end_time' => '21:00:00',
                    'location' => 'Online via Zoom',
                    'venue' => 'Virtual Event',
                    'city' => 'Online',
                    'province' => 'Online',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 500,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Talkshow financial planning yang akan mengubah mindset keuangan Anda:</p><ol><li>E-Certificate keikutsertaan talkshow financial planning</li><li>Recording access untuk dapat menonton ulang materi kapan saja</li><li>Financial Planning Template Excel untuk membuat rencana keuangan personal</li><li>E-Book Investasi lengkap untuk pemula hingga menengah</li><li>Join Telegram Community eksklusif dengan financial advisor dan investor</li><li>Free consultation 30 menit dengan certified financial planner</li></ol>',
                    'requirements' => 'Koneksi internet stabil, Aplikasi Zoom, Email aktif',
                    'organizer_name' => 'HASTANA Financial Academy',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567897',
                    'tags' => json_encode(['financial-planning', 'talkshow', 'investment', 'free-event', 'online']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Seminar Leadership Excellence: Leading in Digital Era',
                    'slug' => 'seminar-leadership-excellence-digital-era',
                    'image' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Seminar kepemimpinan untuk para leader dan calon leader di era digital.</p><p><strong>Materi:</strong></p><ul><li>Digital Leadership Mindset</li><li>Leading Remote Teams</li><li>Change Management</li><li>Innovation & Agility</li><li>People Development</li></ul><p><strong>Target:</strong> Manager, Supervisor, Team Leader</p>',
                    'short_description' => 'Seminar kepemimpinan untuk leader di era digital.',
                    'start_date' => '2025-12-18',
                    'end_date' => '2025-12-18',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Hotel Borobudur Jakarta',
                    'venue' => 'Ballroom 2',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 1500000,
                    'quota' => 100,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Seminar leadership yang akan meningkatkan kapasitas kepemimpinan Anda:</p><ol><li>Sertifikat Resmi HASTANA Leadership Institute yang diakui industri</li><li>Lunch dan Coffee Break premium dengan menu berkualitas</li><li>Modul Leadership komprehensif dengan tools dan framework terkini</li><li>Networking session eksklusif dengan senior leaders dari berbagai industri</li><li>1 bulan online coaching personal dengan certified leadership coach</li><li>Access ke komunitas leader alumni untuk continuous learning</li></ol>',
                    'requirements' => 'Posisi managerial atau team leader, Minimal 3 tahun pengalaman kerja',
                    'organizer_name' => 'HASTANA Leadership Institute',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567898',
                    'tags' => json_encode(['leadership', 'seminar', 'management', 'digital-transformation']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
            ]);
        }

        // ============================================
        // KATEGORI 3: WEDDING EXPO (5 events)
        // ============================================
        $weddingCategory = $categories->where('slug', 'wedding-expo')->first();
        if ($weddingCategory) {
            $allEvents = array_merge($allEvents, [
                [
                    'title' => 'Wedding Expo Jakarta 2025: Your Dream Wedding Starts Here',
                    'slug' => 'wedding-expo-jakarta-2025-your-dream-wedding-starts-here',
                    'image' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Pameran pernikahan terbesar di Jakarta dengan 200+ vendor wedding terbaik!</p><p><strong>Vendor yang hadir:</strong></p><ul><li>Wedding Organizer & Planner</li><li>Catering & Venue</li><li>Photography & Videography</li><li>Bridal & Makeup Artist</li><li>Wedding Decoration</li><li>Entertainment & Music</li><li>Honeymoon Packages</li></ul><p><strong>Special Promo:</strong> Diskon hingga 50% untuk booking di hari event!</p>',
                    'short_description' => 'Pameran pernikahan terbesar di Jakarta dengan 200+ vendor wedding terbaik.',
                    'start_date' => '2025-11-29',
                    'end_date' => '2025-12-01',
                    'start_time' => '10:00:00',
                    'end_time' => '21:00:00',
                    'location' => 'Jakarta Convention Center (JCC)',
                    'venue' => 'Hall A-B-C',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 10000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Wedding Expo terbesar yang memberikan kemudahan perencanaan pernikahan:</p><ol><li>Free Entry ke pameran pernikahan terbesar di Jakarta tanpa biaya masuk</li><li>Wedding Planning Guide Book lengkap dengan checklist dan timeline</li><li>Voucher dan promo eksklusif dari 200+ vendor wedding terpilih</li><li>Doorprize honeymoon package ke destinasi romantis dalam dan luar negeri</li><li>Free konsultasi dengan wedding planner berpengalaman di booth khusus</li><li>Akses ke fashion show dan live entertainment sepanjang hari</li></ol>',
                    'requirements' => 'Registrasi online (dapat dilakukan on-site), Pasangan yang akan menikah atau keluarga',
                    'organizer_name' => 'HASTANA Wedding Exhibition',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567899',
                    'tags' => json_encode(['wedding', 'expo', 'jakarta', 'free-event', 'bridal']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Bandung Bridal Fair 2025',
                    'slug' => 'bandung-bridal-fair-2025',
                    'image' => 'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Pameran pernikahan eksklusif di Bandung dengan vendor pilihan dan fashion show.</p><p><strong>Highlight:</strong></p><ul><li>150+ Premium Wedding Vendors</li><li>Bridal Fashion Show</li><li>Wedding Talk & Tips</li><li>Live Music Performance</li><li>Photo Booth</li></ul><p>Dapatkan paket pernikahan impian Anda dengan harga spesial!</p>',
                    'short_description' => 'Pameran pernikahan eksklusif di Bandung dengan vendor pilihan.',
                    'start_date' => '2025-12-13',
                    'end_date' => '2025-12-14',
                    'start_time' => '10:00:00',
                    'end_time' => '20:00:00',
                    'location' => 'Trans Luxury Hotel Bandung',
                    'venue' => 'Grand Ballroom',
                    'city' => 'Bandung',
                    'province' => 'Jawa Barat',
                    'is_free' => false,
                    'price' => 50000,
                    'quota' => 3000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Bridal Fair eksklusif Bandung memberikan pengalaman pernikahan yang tak terlupakan:</p><ol><li>Welcome Drink premium untuk menyambut kedatangan Anda</li><li>Wedding Guide Magazine edisi khusus Bandung dengan vendor terpilih</li><li>Exclusive Promo dan Voucher dari vendor premium pilihan</li><li>Fashion Show Access untuk melihat tren wedding dress terkini</li><li>Goodie Bag berisi sample produk dan voucher dari berbagai vendor</li><li>Photo session dengan backdrop wedding yang instagramable</li></ol>',
                    'requirements' => 'Registrasi online atau beli tiket on-site',
                    'organizer_name' => 'HASTANA Bandung Wedding',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567900',
                    'tags' => json_encode(['wedding', 'expo', 'bandung', 'bridal', 'fashion-show']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Surabaya Wedding Festival 2025',
                    'slug' => 'surabaya-wedding-festival-2025',
                    'image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Festival pernikahan terbesar di Jawa Timur dengan konsep modern dan tradisional.</p><p><strong>Fasilitas:</strong></p><ul><li>100+ Wedding Vendors</li><li>Traditional & Modern Wedding Display</li><li>Prewedding Spot</li><li>Wedding Cake Competition</li><li>Live Entertainment</li></ul>',
                    'short_description' => 'Festival pernikahan terbesar di Jawa Timur.',
                    'start_date' => '2025-11-08',
                    'end_date' => '2025-11-10',
                    'start_time' => '10:00:00',
                    'end_time' => '21:00:00',
                    'location' => 'Grand City Convention Hall Surabaya',
                    'venue' => 'Main Hall',
                    'city' => 'Surabaya',
                    'province' => 'Jawa Timur',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 5000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Festival pernikahan terbesar Jawa Timur dengan berbagai keuntungan:</p><ol><li>Free Entry ke festival pernikahan dengan 100+ vendor terpilih</li><li>Wedding Planner Consultation gratis dengan expert berpengalaman</li><li>Vendor Promo hingga 40% untuk booking di hari event</li><li>Photo Booth Access dengan tema traditional dan modern wedding</li><li>Doorprize menarik termasuk paket dekorasi dan catering</li><li>Live entertainment dan wedding cake competition yang seru</li></ol>',
                    'requirements' => 'Registrasi online recommended (walk-in welcome)',
                    'organizer_name' => 'HASTANA Surabaya Wedding Expo',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567901',
                    'tags' => json_encode(['wedding', 'expo', 'surabaya', 'free-event', 'festival']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Intimate Wedding Workshop & Expo Bali',
                    'slug' => 'intimate-wedding-workshop-expo-bali',
                    'image' => 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Workshop dan expo khusus intimate wedding di destinasi pernikahan favorit, Bali.</p><p><strong>Acara:</strong></p><ul><li>Workshop Planning Intimate Wedding</li><li>Bali Wedding Vendors Showcase</li><li>Beach Wedding Simulation</li><li>Destination Wedding Tips</li><li>Meet & Greet Wedding Celebrities</li></ul>',
                    'short_description' => 'Workshop dan expo khusus intimate wedding di Bali.',
                    'start_date' => '2025-12-20',
                    'end_date' => '2025-12-21',
                    'start_time' => '10:00:00',
                    'end_time' => '18:00:00',
                    'location' => 'The Mulia Resort Bali',
                    'venue' => 'Ocean View Ballroom',
                    'city' => 'Badung',
                    'province' => 'Bali',
                    'is_free' => false,
                    'price' => 150000,
                    'quota' => 500,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Workshop dan expo intimate wedding di Bali memberikan value ekslusif:</p><ol><li>Workshop Access ke semua sesi intimate wedding planning dan tips</li><li>Lunch premium dengan menu khas Bali di resort bintang 5</li><li>Bali Wedding Guide lengkap dengan vendor dan venue recommendation</li><li>Exclusive Vendor Discount khusus untuk intimate wedding package</li><li>Resort Tour ke area pernikahan dengan pemandangan ocean view</li><li>Meet and greet session dengan wedding celebrities dan influencer</li></ol>',
                    'requirements' => 'Pre-registration online, Pasangan yang menikah 2025-2026',
                    'organizer_name' => 'HASTANA Bali Wedding',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567902',
                    'tags' => json_encode(['wedding', 'expo', 'bali', 'intimate-wedding', 'destination-wedding']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
                [
                    'title' => 'Muslim Wedding Expo 2025',
                    'slug' => 'muslim-wedding-expo-2025',
                    'image' => 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Pameran pernikahan islami dengan vendor yang sesuai syariah dan konsep pernikahan muslim modern.</p><p><strong>Vendor Syariah:</strong></p><ul><li>Halal Catering</li><li>Syariah Wedding Organizer</li><li>Muslimah Bridal & MUA</li><li>Akad Nikah Package</li><li>Islamic Decoration</li><li>Nasyid & Marawis Entertainment</li></ul>',
                    'short_description' => 'Pameran pernikahan islami dengan vendor syariah.',
                    'start_date' => '2025-11-15',
                    'end_date' => '2025-11-16',
                    'start_time' => '10:00:00',
                    'end_time' => '20:00:00',
                    'location' => 'Islamic Center Jakarta',
                    'venue' => 'Main Hall',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 4000,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Muslim Wedding Expo dengan nuansa islami yang penuh berkah:</p><ol><li>Free Entry ke pameran pernikahan islami dengan vendor syariah terpilih</li><li>Islamic Wedding Guide lengkap sesuai sunnah dan syariah</li><li>Prewedding Hijab Styling Tips dari makeup artist muslimah professional</li><li>Vendor Promo khusus untuk paket pernikahan syariah dan halal</li><li>Al-Quran Doorprize edisi khusus dan hampers islami lainnya</li><li>Kajian singkat tentang adab pernikahan dalam Islam</li></ol>',
                    'requirements' => 'Registrasi online, Dress code sopan (muslimah disarankan berhijab)',
                    'organizer_name' => 'HASTANA Islamic Wedding',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567903',
                    'tags' => json_encode(['wedding', 'expo', 'islamic', 'muslim', 'free-event', 'syariah']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
            ]);
        }

        // ============================================
        // KATEGORI 4: SERTIFIKASI HASTANA (5 events)
        // ============================================
        $sertifikasiCategory = $categories->where('slug', 'sertifikasi-hastana')->first();
        if ($sertifikasiCategory) {
            $allEvents = array_merge($allEvents, [
                [
                    'title' => 'Sertifikasi Wedding Organizer Profesional',
                    'slug' => 'sertifikasi-wedding-organizer-profesional',
                    'image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program sertifikasi resmi untuk menjadi Wedding Organizer profesional yang diakui industri.</p><p><strong>Materi Sertifikasi:</strong></p><ul><li>Wedding Industry Overview</li><li>Wedding Planning & Management</li><li>Vendor Coordination</li><li>Budget & Timeline Management</li><li>Problem Solving on Wedding Day</li><li>Marketing & Branding for WO</li><li>Legal & Contract</li></ul><p><strong>Benefit:</strong> Sertifikat resmi HASTANA yang diakui industri pernikahan Indonesia</p>',
                    'short_description' => 'Program sertifikasi resmi Wedding Organizer profesional.',
                    'start_date' => '2025-11-18',
                    'end_date' => '2025-11-22',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA Training Center Jakarta',
                    'venue' => 'Training Room 1',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 5000000,
                    'quota' => 20,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Program sertifikasi Wedding Organizer yang memberikan kredensial profesional:</p><ol><li>Sertifikat Resmi HASTANA yang diakui industri pernikahan Indonesia</li><li>Modul lengkap mencakup semua aspek wedding planning dan management</li><li>Lunch dan Coffee Break premium selama 5 hari pelatihan</li><li>Ujian sertifikasi komprehensif untuk memastikan kompetensi</li><li>3 bulan mentoring personal dengan senior wedding organizer</li><li>Join Alumni Network untuk networking dan referral bisnis</li></ol>',
                    'requirements' => 'Minimal SMA/sederajat, Memiliki passion di wedding industry, Membawa laptop',
                    'organizer_name' => 'HASTANA Certification Board',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567904',
                    'tags' => json_encode(['sertifikasi', 'wedding-organizer', 'professional', 'career']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Sertifikasi Event Organizer & MICE Professional',
                    'slug' => 'sertifikasi-event-organizer-mice-professional',
                    'image' => 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program sertifikasi untuk Event Organizer dan MICE (Meeting, Incentive, Convention, Exhibition) Professional.</p><p><strong>Kurikulum:</strong></p><ul><li>Event Management Fundamentals</li><li>MICE Industry Standards</li><li>Event Marketing & Sponsorship</li><li>Venue & Logistics Management</li><li>Risk Management</li><li>Post-Event Evaluation</li></ul>',
                    'short_description' => 'Program sertifikasi Event Organizer dan MICE Professional.',
                    'start_date' => '2025-12-02',
                    'end_date' => '2025-12-06',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA Training Center Jakarta',
                    'venue' => 'Training Room 2',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 6000000,
                    'quota' => 20,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Sertifikasi Event Organizer dan MICE Professional yang comprehensive:</p><ol><li>Sertifikat HASTANA MICE Professional yang diakui industri event nasional</li><li>Modul dan Case Study dari event-event besar nasional dan internasional</li><li>Lunch berkualitas selama 5 hari intensive training</li><li>Field Study langsung ke event besar untuk pengalaman praktis</li><li>Ujian Sertifikasi yang menguji kemampuan teoretis dan praktis</li><li>Lifetime Alumni Support untuk konsultasi dan pengembangan karir</li></ol>',
                    'requirements' => 'Minimal D3/S1, Pengalaman event minimal 1 tahun (diutamakan), Laptop',
                    'organizer_name' => 'HASTANA Certification Board',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567905',
                    'tags' => json_encode(['sertifikasi', 'event-organizer', 'mice', 'professional']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
                [
                    'title' => 'Sertifikasi Digital Marketing Specialist',
                    'slug' => 'sertifikasi-digital-marketing-specialist',
                    'image' => 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program sertifikasi digital marketing dengan kurikulum terkini dan praktek langsung.</p><p><strong>Materi:</strong></p><ul><li>Digital Marketing Strategy</li><li>SEO & SEM</li><li>Social Media Marketing</li><li>Content Marketing</li><li>Email Marketing</li><li>Analytics & Reporting</li><li>Paid Advertising (Google Ads, Meta Ads)</li></ul><p>Termasuk ujian sertifikasi dan capstone project!</p>',
                    'short_description' => 'Program sertifikasi Digital Marketing Specialist.',
                    'start_date' => '2025-11-11',
                    'end_date' => '2025-11-15',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA Digital Academy',
                    'venue' => 'Lab Digital Marketing',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 4500000,
                    'quota' => 25,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Sertifikasi Digital Marketing Specialist yang membuka peluang karir luas:</p><ol><li>Sertifikat HASTANA Digital Marketing Specialist yang diakui industri digital</li><li>Modul Digital lengkap dengan akses selamanya untuk update materi</li><li>Lunch dan Snack berkualitas selama 5 hari intensive training</li><li>Akses ke premium tools dan template untuk campaign digital marketing</li><li>2 bulan konsultasi personal untuk mengimplementasikan ilmu di pekerjaan</li><li>Job Connector dengan perusahaan partner untuk peluang karir</li></ol>',
                    'requirements' => 'Minimal SMA, Familiar dengan internet & social media, Laptop dengan internet',
                    'organizer_name' => 'HASTANA Digital Academy',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567906',
                    'tags' => json_encode(['sertifikasi', 'digital-marketing', 'specialist', 'online-marketing']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Sertifikasi Project Management Professional (PMP Preparation)',
                    'slug' => 'sertifikasi-project-management-pmp-preparation',
                    'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program persiapan sertifikasi Project Management Professional dengan standar internasional.</p><p><strong>Coverage:</strong></p><ul><li>Project Management Framework</li><li>Initiating & Planning</li><li>Executing & Monitoring</li><li>Controlling & Closing</li><li>Agile & Hybrid Approaches</li><li>PMP Exam Simulation</li></ul>',
                    'short_description' => 'Program persiapan sertifikasi Project Management Professional.',
                    'start_date' => '2025-12-09',
                    'end_date' => '2025-12-13',
                    'start_time' => '09:00:00',
                    'end_time' => '18:00:00',
                    'location' => 'HASTANA Professional Institute',
                    'venue' => 'Executive Training Room',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 8000000,
                    'quota' => 15,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Program persiapan PMP yang comprehensive untuk kesuksesan sertifikasi:</p><ol><li>Sertifikat HASTANA PMP Preparation sebagai bukti penyelesaian training</li><li>PMBOK Guide edisi terbaru sebagai referensi utama project management</li><li>Lunch dan Coffee Break premium selama 5 hari intensive preparation</li><li>500+ Practice Questions untuk latihan soal ujian PMP yang sesungguhnya</li><li>Exam Voucher Discount untuk menghemat biaya ujian PMP resmi</li><li>6 bulan Study Group dengan sesama kandidat PMP untuk saling support</li></ol>',
                    'requirements' => 'Minimal S1, 3 tahun pengalaman project management, Laptop',
                    'organizer_name' => 'HASTANA Professional Institute',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567907',
                    'tags' => json_encode(['sertifikasi', 'project-management', 'pmp', 'professional']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
                [
                    'title' => 'Sertifikasi HR Professional & Talent Management',
                    'slug' => 'sertifikasi-hr-professional-talent-management',
                    'image' => 'https://images.unsplash.com/photo-1521791136064-7986c2920216?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program sertifikasi untuk HR Professional dengan fokus pada talent management dan people development.</p><p><strong>Materi:</strong></p><ul><li>Strategic HRM</li><li>Talent Acquisition & Recruitment</li><li>Performance Management</li><li>Learning & Development</li><li>Compensation & Benefits</li><li>Employee Relations</li><li>HR Analytics</li></ul>',
                    'short_description' => 'Program sertifikasi HR Professional dan Talent Management.',
                    'start_date' => '2025-11-25',
                    'end_date' => '2025-11-29',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA HR Institute',
                    'venue' => 'Training Hall',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 5500000,
                    'quota' => 20,
                    'max_participants' => 0,
                    'current_participants' => 0,
                    'benefits' => '<p>Sertifikasi HR Professional yang meningkatkan credibility dan expertise:</p><ol><li>Sertifikat HASTANA HR Professional yang diakui industri dan perusahaan</li><li>Modul dan Template HR lengkap untuk berbagai proses HR management</li><li>Lunch berkualitas selama 5 hari pelatihan intensif</li><li>HR Tools dan Software Trial untuk modernisasi proses HR</li><li>Ujian Sertifikasi komprehensif yang menguji seluruh aspek HR</li><li>HR Community Access untuk networking dengan HR leader Indonesia</li></ol>',
                    'requirements' => 'Minimal D3, Bekerja di HR atau tertarik karir HR, Laptop',
                    'organizer_name' => 'HASTANA HR Institute',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567908',
                    'tags' => json_encode(['sertifikasi', 'hr', 'human-resource', 'talent-management']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
            ]);
        }

        // Insert semua events dengan handling foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        foreach ($allEvents as $eventData) {
            try {
                EventHastana::create($eventData);
            } catch (\Exception $e) {
                $this->command->error("❌ Error creating event: {$eventData['title']}");
                $this->command->error("   Error: " . $e->getMessage());
            }
        }
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('✅ Event Hastana seeder berhasil dijalankan!');
        $this->command->info('   📋 Total events created: ' . count($allEvents));
        $this->command->line('');
        $this->command->info('   📊 Breakdown per kategori:');
        
        if ($workshopCategory) {
            $workshopCount = EventHastana::where('event_category_id', $workshopCategory->id)->count();
            $this->command->info("   - {$workshopCategory->name}: {$workshopCount} events");
        }
        if ($seminarCategory) {
            $seminarCount = EventHastana::where('event_category_id', $seminarCategory->id)->count();
            $this->command->info("   - {$seminarCategory->name}: {$seminarCount} events");
        }
        if ($weddingCategory) {
            $weddingCount = EventHastana::where('event_category_id', $weddingCategory->id)->count();
            $this->command->info("   - {$weddingCategory->name}: {$weddingCount} events");
        }
        if ($sertifikasiCategory) {
            $sertifikasiCount = EventHastana::where('event_category_id', $sertifikasiCategory->id)->count();
            $this->command->info("   - {$sertifikasiCategory->name}: {$sertifikasiCount} events");
        }
    }
}
