<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\EventHastana;
use App\Models\EventCategory;
use Illuminate\Support\Str;

class EventHastanaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ambil semua kategori
        $categories = EventCategory::all();
        
        if ($categories->isEmpty()) {
            $this->command->warn('Event categories tidak ditemukan. Jalankan EventCategorySeeder terlebih dahulu.');
            return;
        }

        $allEvents = [];

        // ============================================
        // KATEGORI 1: WORKSHOP & PELATIHAN (5 events)
        // ============================================
        $workshopCategory = $categories->where('slug', 'workshop-pelatihan')->first();
        if ($workshopCategory) {
            $allEvents = array_merge($allEvents, [
                [
                    'title' => 'Workshop Digital Marketing & Social Media Strategy 2025',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Workshop intensif 2 hari tentang strategi digital marketing terkini untuk meningkatkan brand awareness dan penjualan bisnis Anda.</p><p><strong>Materi yang akan dibahas:</strong></p><ul><li>Social Media Marketing Strategy (Instagram, TikTok, LinkedIn)</li><li>Content Marketing & SEO Optimization</li><li>Facebook & Instagram Ads</li><li>Google Ads & Analytics</li><li>Email Marketing Automation</li><li>Influencer Marketing</li></ul><p><strong>Instruktur:</strong> Tim praktisi digital marketing dengan pengalaman 10+ tahun di berbagai industri</p>',
                    'short_description' => 'Workshop intensif strategi digital marketing untuk meningkatkan brand awareness dan penjualan bisnis.',
                    'start_date' => '2025-11-15',
                    'end_date' => '2025-11-16',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Jakarta Convention Center',
                    'venue' => 'Ruang Seminar A, Lantai 3',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 500000,
                    'quota' => 50,
                    'max_participants' => 50,
                    'current_participants' => 23,
                    'benefits' => 'E-Certificate, Lunch & Coffee Break 2 Hari, Modul Digital Marketing, Template Campaign, Free Konsultasi 1 Bulan, Akses Komunitas Digital Marketer',
                    'requirements' => 'Membawa laptop, Email aktif untuk akses materi, Memiliki akun social media',
                    'organizer_name' => 'HASTANA Indonesia',
                    'contact_email' => 'workshop@hastana.id',
                    'contact_phone' => '081234567890',
                    'tags' => json_encode(['digital-marketing', 'workshop', 'business', 'social-media', 'seo']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Workshop Content Creation: Fotografi & Videografi untuk Bisnis',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Workshop praktis membuat konten visual menarik untuk meningkatkan engagement di social media bisnis Anda.</p><p><strong>Materi meliputi:</strong></p><ul><li>Dasar Fotografi Produk</li><li>Teknik Lighting & Komposisi</li><li>Video Marketing untuk Instagram Reels & TikTok</li><li>Mobile Photography & Editing</li><li>Copywriting untuk Visual Content</li><li>Planning & Scheduling Content</li></ul>',
                    'short_description' => 'Workshop praktis fotografi dan videografi untuk konten bisnis yang engaging.',
                    'start_date' => '2025-12-08',
                    'end_date' => '2025-12-08',
                    'start_time' => '09:00:00',
                    'end_time' => '16:00:00',
                    'location' => 'Coworking Space Jakarta',
                    'venue' => 'Studio Room & Meeting Room 1',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 350000,
                    'quota' => 30,
                    'max_participants' => 30,
                    'current_participants' => 18,
                    'benefits' => 'E-Certificate, Lunch & Coffee Break, Modul Content Creation, Template Design, Preset Editing',
                    'requirements' => 'Smartphone dengan kamera bagus atau kamera DSLR/Mirrorless, Laptop (optional)',
                    'organizer_name' => 'HASTANA Creative Studio',
                    'contact_email' => 'workshop@hastana.id',
                    'contact_phone' => '081234567890',
                    'tags' => json_encode(['content-creation', 'workshop', 'fotografi', 'videografi', 'social-media']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Pelatihan Microsoft Excel Advanced untuk Profesional',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Pelatihan intensif Microsoft Excel tingkat lanjut untuk meningkatkan produktivitas kerja.</p><p><strong>Materi:</strong></p><ul><li>Advanced Formula & Functions</li><li>Pivot Tables & Charts</li><li>Data Analysis & Visualization</li><li>Macro & VBA Automation</li><li>Dashboard Creation</li><li>Power Query & Power Pivot</li></ul>',
                    'short_description' => 'Pelatihan Excel tingkat lanjut untuk meningkatkan produktivitas kerja.',
                    'start_date' => '2025-11-25',
                    'end_date' => '2025-11-26',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA Training Center',
                    'venue' => 'Lab Komputer 1',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 750000,
                    'quota' => 20,
                    'max_participants' => 20,
                    'current_participants' => 12,
                    'benefits' => 'Sertifikat Resmi, Lunch & Coffee Break, Modul Excel, File Latihan, Free Update Materi Selamanya',
                    'requirements' => 'Laptop dengan MS Excel 2016 atau lebih baru, Dasar Excel (formula sederhana)',
                    'organizer_name' => 'HASTANA Training Center',
                    'contact_email' => 'training@hastana.id',
                    'contact_phone' => '081234567891',
                    'tags' => json_encode(['excel', 'workshop', 'productivity', 'data-analysis', 'microsoft-office']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => false,
                ],
                [
                    'title' => 'Workshop Graphic Design dengan Adobe Photoshop & Illustrator',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Workshop praktis desain grafis menggunakan Adobe Photoshop dan Illustrator untuk pemula hingga menengah.</p><p><strong>Yang akan dipelajari:</strong></p><ul><li>Fundamental Design Principles</li><li>Adobe Photoshop: Photo Editing & Manipulation</li><li>Adobe Illustrator: Vector Design & Logo Creation</li><li>Typography & Color Theory</li><li>Social Media Design Assets</li><li>Portfolio Creation</li></ul>',
                    'short_description' => 'Workshop desain grafis dengan Photoshop & Illustrator untuk pemula hingga menengah.',
                    'start_date' => '2025-12-15',
                    'end_date' => '2025-12-15',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Design Studio Bandung',
                    'venue' => 'Creative Space',
                    'city' => 'Bandung',
                    'province' => 'Jawa Barat',
                    'is_free' => false,
                    'price' => 450000,
                    'quota' => 25,
                    'max_participants' => 25,
                    'current_participants' => 15,
                    'benefits' => 'E-Certificate, Lunch & Coffee Break, Modul Design, Template & Mockup Pack, Free Konsultasi Portfolio',
                    'requirements' => 'Laptop dengan Adobe Photoshop & Illustrator terinstall, Mouse (sangat disarankan)',
                    'organizer_name' => 'HASTANA Creative Academy',
                    'contact_email' => 'workshop@hastana.id',
                    'contact_phone' => '081234567892',
                    'tags' => json_encode(['graphic-design', 'workshop', 'photoshop', 'illustrator', 'design']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
                [
                    'title' => 'Workshop Public Speaking & Communication Skills',
                    'event_category_id' => $workshopCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Workshop interaktif untuk meningkatkan kemampuan berbicara di depan umum dan komunikasi efektif.</p><p><strong>Materi workshop:</strong></p><ul><li>Mengatasi Demam Panggung</li><li>Teknik Vokal & Body Language</li><li>Storytelling yang Menarik</li><li>Persuasive Communication</li><li>Q&A Handling</li><li>Praktik Langsung & Video Review</li></ul>',
                    'short_description' => 'Workshop interaktif public speaking dan komunikasi efektif.',
                    'start_date' => '2025-11-30',
                    'end_date' => '2025-11-30',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Hotel Santika Surabaya',
                    'venue' => 'Function Room 1',
                    'city' => 'Surabaya',
                    'province' => 'Jawa Timur',
                    'is_free' => false,
                    'price' => 400000,
                    'quota' => 35,
                    'max_participants' => 35,
                    'current_participants' => 22,
                    'benefits' => 'E-Certificate, Lunch & Coffee Break, Modul Public Speaking, Video Rekaman Presentasi, 1 Bulan Mentoring Online',
                    'requirements' => 'Tidak ada requirement khusus, cocok untuk pemula',
                    'organizer_name' => 'HASTANA Communication Institute',
                    'contact_email' => 'workshop@hastana.id',
                    'contact_phone' => '081234567893',
                    'tags' => json_encode(['public-speaking', 'workshop', 'communication', 'soft-skills']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
            ]);
        }

        // ============================================
        // KATEGORI 2: SEMINAR & TALKSHOW (5 events)
        // ============================================
        $seminarCategory = $categories->where('slug', 'seminar-talkshow')->first();
        if ($seminarCategory) {
            $allEvents = array_merge($allEvents, [
                [
                    'title' => 'Seminar Kewirausahaan: From Zero to Hero',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Seminar inspiratif bersama para entrepreneur sukses yang memulai bisnis dari nol hingga mencapai kesuksesan luar biasa.</p><p><strong>Pembicara:</strong></p><ul><li>Budi Santoso - Founder Tech Startup Unicorn (Valuasi $1B+)</li><li>Siti Nurhaliza - CEO E-Commerce Fashion Terbesar</li><li>Ahmad Dhani - Owner 100+ Franchise F&B di Indonesia</li><li>Linda Wijaya - Social Media Influencer & Business Owner</li></ul><p>Dapatkan insight langsung dari perjalanan mereka membangun bisnis dari nol!</p>',
                    'short_description' => 'Seminar inspiratif bersama entrepreneur sukses yang memulai bisnis dari nol hingga sukses.',
                    'start_date' => '2025-12-05',
                    'end_date' => '2025-12-05',
                    'start_time' => '13:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Ballroom Hotel Santika',
                    'venue' => 'Grand Ballroom',
                    'city' => 'Bandung',
                    'province' => 'Jawa Barat',
                    'is_free' => false,
                    'price' => 250000,
                    'quota' => 200,
                    'max_participants' => 200,
                    'current_participants' => 87,
                    'benefits' => 'E-Certificate, Snack & Refreshment, Networking Session, Business Plan Template, Doorprize Menarik, Akses Recording',
                    'requirements' => 'Minat di bidang wirausaha, Membawa kartu identitas',
                    'organizer_name' => 'HASTANA Indonesia x Komunitas Wirausaha Muda',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567894',
                    'tags' => json_encode(['entrepreneurship', 'seminar', 'business', 'startup', 'inspirasi']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Talkshow: Future of Technology & Innovation 2025',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Talkshow eksklusif membahas tren teknologi terkini dan masa depan inovasi digital.</p><p><strong>Topik Diskusi:</strong></p><ul><li>Artificial Intelligence & Machine Learning</li><li>Blockchain & Web3</li><li>Internet of Things (IoT)</li><li>Metaverse & Virtual Reality</li><li>Sustainable Technology</li></ul><p><strong>Narasumber:</strong> Tech Leaders dari Google, Microsoft, dan Startup Indonesia</p>',
                    'short_description' => 'Talkshow tentang tren teknologi dan inovasi digital masa depan.',
                    'start_date' => '2025-11-22',
                    'end_date' => '2025-11-22',
                    'start_time' => '14:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Auditorium Universitas Indonesia',
                    'venue' => 'Auditorium Utama',
                    'city' => 'Depok',
                    'province' => 'Jawa Barat',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 300,
                    'max_participants' => 300,
                    'current_participants' => 156,
                    'benefits' => 'E-Certificate, Snack & Refreshment, Networking Session, Akses Materi PDF, Doorprize Gadget',
                    'requirements' => 'Registrasi online, Mahasiswa/Umum dipersilakan',
                    'organizer_name' => 'HASTANA Indonesia x UI Computer Science',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567895',
                    'tags' => json_encode(['technology', 'talkshow', 'innovation', 'ai', 'free-event']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Seminar Kesehatan Mental di Tempat Kerja',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Seminar penting tentang menjaga kesehatan mental di lingkungan kerja yang dinamis dan penuh tekanan.</p><p><strong>Materi:</strong></p><ul><li>Mengenali Tanda-tanda Burnout</li><li>Stress Management Techniques</li><li>Work-Life Balance</li><li>Building Resilience</li><li>Mental Health First Aid</li></ul><p><strong>Pembicara:</strong> Psikolog Klinis dan HR Professionals</p>',
                    'short_description' => 'Seminar tentang menjaga kesehatan mental di lingkungan kerja.',
                    'start_date' => '2025-11-28',
                    'end_date' => '2025-11-28',
                    'start_time' => '14:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Auditorium Universitas Gadjah Mada',
                    'venue' => 'Auditorium Psikologi',
                    'city' => 'Yogyakarta',
                    'province' => 'DI Yogyakarta',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 250,
                    'max_participants' => 250,
                    'current_participants' => 123,
                    'benefits' => 'E-Certificate, Snack, Konseling Gratis 1x, Modul Mental Health, Relaksasi Session',
                    'requirements' => 'Registrasi online, Terbuka untuk umum',
                    'organizer_name' => 'HASTANA Indonesia x UGM Psychology',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567896',
                    'tags' => json_encode(['mental-health', 'seminar', 'workplace', 'free-event', 'wellbeing']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Talkshow Financial Planning untuk Generasi Milenial & Gen Z',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Talkshow interaktif tentang perencanaan keuangan untuk generasi muda.</p><p><strong>Topik:</strong></p><ul><li>Budgeting & Saving Tips</li><li>Investasi untuk Pemula</li><li>Passive Income Strategy</li><li>Crypto & Digital Assets</li><li>Retirement Planning di Usia Muda</li></ul><p><strong>Pembicara:</strong> Certified Financial Planner & Successful Young Investor</p>',
                    'short_description' => 'Talkshow financial planning untuk generasi milenial dan Gen Z.',
                    'start_date' => '2025-12-12',
                    'end_date' => '2025-12-12',
                    'start_time' => '19:00:00',
                    'end_time' => '21:00:00',
                    'location' => 'Online via Zoom',
                    'venue' => 'Virtual Event',
                    'city' => 'Online',
                    'province' => 'Online',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 500,
                    'max_participants' => 500,
                    'current_participants' => 278,
                    'benefits' => 'E-Certificate, Recording Access, Financial Planning Template, E-Book Investasi, Join Telegram Community',
                    'requirements' => 'Koneksi internet stabil, Aplikasi Zoom, Email aktif',
                    'organizer_name' => 'HASTANA Financial Academy',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567897',
                    'tags' => json_encode(['financial-planning', 'talkshow', 'investment', 'free-event', 'online']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Seminar Leadership Excellence: Leading in Digital Era',
                    'event_category_id' => $seminarCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Seminar kepemimpinan untuk para leader dan calon leader di era digital.</p><p><strong>Materi:</strong></p><ul><li>Digital Leadership Mindset</li><li>Leading Remote Teams</li><li>Change Management</li><li>Innovation & Agility</li><li>People Development</li></ul><p><strong>Target:</strong> Manager, Supervisor, Team Leader</p>',
                    'short_description' => 'Seminar kepemimpinan untuk leader di era digital.',
                    'start_date' => '2025-12-18',
                    'end_date' => '2025-12-18',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'Hotel Borobudur Jakarta',
                    'venue' => 'Ballroom 2',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 1500000,
                    'quota' => 100,
                    'max_participants' => 100,
                    'current_participants' => 45,
                    'benefits' => 'Sertifikat Resmi, Lunch & Coffee Break, Modul Leadership, Networking Session, 1 Bulan Online Coaching',
                    'requirements' => 'Posisi managerial atau team leader, Minimal 3 tahun pengalaman kerja',
                    'organizer_name' => 'HASTANA Leadership Institute',
                    'contact_email' => 'seminar@hastana.id',
                    'contact_phone' => '081234567898',
                    'tags' => json_encode(['leadership', 'seminar', 'management', 'digital-transformation']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
            ]);
        }

        // ============================================
        // KATEGORI 3: WEDDING EXPO (5 events)
        // ============================================
        $weddingCategory = $categories->where('slug', 'wedding-expo')->first();
        if ($weddingCategory) {
            $allEvents = array_merge($allEvents, [
                [
                    'title' => 'Wedding Expo Jakarta 2025: Your Dream Wedding Starts Here',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Pameran pernikahan terbesar di Jakarta dengan 200+ vendor wedding terbaik!</p><p><strong>Vendor yang hadir:</strong></p><ul><li>Wedding Organizer & Planner</li><li>Catering & Venue</li><li>Photography & Videography</li><li>Bridal & Makeup Artist</li><li>Wedding Decoration</li><li>Entertainment & Music</li><li>Honeymoon Packages</li></ul><p><strong>Special Promo:</strong> Diskon hingga 50% untuk booking di hari event!</p>',
                    'short_description' => 'Pameran pernikahan terbesar di Jakarta dengan 200+ vendor wedding terbaik.',
                    'start_date' => '2025-11-29',
                    'end_date' => '2025-12-01',
                    'start_time' => '10:00:00',
                    'end_time' => '21:00:00',
                    'location' => 'Jakarta Convention Center (JCC)',
                    'venue' => 'Hall A-B-C',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 10000,
                    'max_participants' => 10000,
                    'current_participants' => 2345,
                    'benefits' => 'Free Entry, Wedding Planning Guide Book, Voucher & Promo dari Vendor, Doorprize Honeymoon Package, Free Konsultasi Wedding Planner',
                    'requirements' => 'Registrasi online (dapat dilakukan on-site), Pasangan yang akan menikah atau keluarga',
                    'organizer_name' => 'HASTANA Wedding Exhibition',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567899',
                    'tags' => json_encode(['wedding', 'expo', 'jakarta', 'free-event', 'bridal']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Bandung Bridal Fair 2025',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Pameran pernikahan eksklusif di Bandung dengan vendor pilihan dan fashion show.</p><p><strong>Highlight:</strong></p><ul><li>150+ Premium Wedding Vendors</li><li>Bridal Fashion Show</li><li>Wedding Talk & Tips</li><li>Live Music Performance</li><li>Photo Booth</li></ul><p>Dapatkan paket pernikahan impian Anda dengan harga spesial!</p>',
                    'short_description' => 'Pameran pernikahan eksklusif di Bandung dengan vendor pilihan.',
                    'start_date' => '2025-12-13',
                    'end_date' => '2025-12-14',
                    'start_time' => '10:00:00',
                    'end_time' => '20:00:00',
                    'location' => 'Trans Luxury Hotel Bandung',
                    'venue' => 'Grand Ballroom',
                    'city' => 'Bandung',
                    'province' => 'Jawa Barat',
                    'is_free' => false,
                    'price' => 50000,
                    'quota' => 3000,
                    'max_participants' => 3000,
                    'current_participants' => 567,
                    'benefits' => 'Welcome Drink, Wedding Guide Magazine, Exclusive Promo & Voucher, Fashion Show Access, Goodie Bag',
                    'requirements' => 'Registrasi online atau beli tiket on-site',
                    'organizer_name' => 'HASTANA Bandung Wedding',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567900',
                    'tags' => json_encode(['wedding', 'expo', 'bandung', 'bridal', 'fashion-show']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Surabaya Wedding Festival 2025',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Festival pernikahan terbesar di Jawa Timur dengan konsep modern dan tradisional.</p><p><strong>Fasilitas:</strong></p><ul><li>100+ Wedding Vendors</li><li>Traditional & Modern Wedding Display</li><li>Prewedding Spot</li><li>Wedding Cake Competition</li><li>Live Entertainment</li></ul>',
                    'short_description' => 'Festival pernikahan terbesar di Jawa Timur.',
                    'start_date' => '2025-11-08',
                    'end_date' => '2025-11-10',
                    'start_time' => '10:00:00',
                    'end_time' => '21:00:00',
                    'location' => 'Grand City Convention Hall Surabaya',
                    'venue' => 'Main Hall',
                    'city' => 'Surabaya',
                    'province' => 'Jawa Timur',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 5000,
                    'max_participants' => 5000,
                    'current_participants' => 1234,
                    'benefits' => 'Free Entry, Wedding Planner Consultation, Vendor Promo Up to 40%, Photo Booth Access, Doorprize',
                    'requirements' => 'Registrasi online recommended (walk-in welcome)',
                    'organizer_name' => 'HASTANA Surabaya Wedding Expo',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567901',
                    'tags' => json_encode(['wedding', 'expo', 'surabaya', 'free-event', 'festival']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Intimate Wedding Workshop & Expo Bali',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Workshop dan expo khusus intimate wedding di destinasi pernikahan favorit, Bali.</p><p><strong>Acara:</strong></p><ul><li>Workshop Planning Intimate Wedding</li><li>Bali Wedding Vendors Showcase</li><li>Beach Wedding Simulation</li><li>Destination Wedding Tips</li><li>Meet & Greet Wedding Celebrities</li></ul>',
                    'short_description' => 'Workshop dan expo khusus intimate wedding di Bali.',
                    'start_date' => '2025-12-20',
                    'end_date' => '2025-12-21',
                    'start_time' => '10:00:00',
                    'end_time' => '18:00:00',
                    'location' => 'The Mulia Resort Bali',
                    'venue' => 'Ocean View Ballroom',
                    'city' => 'Badung',
                    'province' => 'Bali',
                    'is_free' => false,
                    'price' => 150000,
                    'quota' => 500,
                    'max_participants' => 500,
                    'current_participants' => 189,
                    'benefits' => 'Workshop Access, Lunch, Bali Wedding Guide, Exclusive Vendor Discount, Resort Tour',
                    'requirements' => 'Pre-registration online, Pasangan yang menikah 2025-2026',
                    'organizer_name' => 'HASTANA Bali Wedding',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567902',
                    'tags' => json_encode(['wedding', 'expo', 'bali', 'intimate-wedding', 'destination-wedding']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
                [
                    'title' => 'Muslim Wedding Expo 2025',
                    'event_category_id' => $weddingCategory->id,
                    'event_type' => 'eksternal',
                    'description' => '<p>Pameran pernikahan islami dengan vendor yang sesuai syariah dan konsep pernikahan muslim modern.</p><p><strong>Vendor Syariah:</strong></p><ul><li>Halal Catering</li><li>Syariah Wedding Organizer</li><li>Muslimah Bridal & MUA</li><li>Akad Nikah Package</li><li>Islamic Decoration</li><li>Nasyid & Marawis Entertainment</li></ul>',
                    'short_description' => 'Pameran pernikahan islami dengan vendor syariah.',
                    'start_date' => '2025-11-15',
                    'end_date' => '2025-11-16',
                    'start_time' => '10:00:00',
                    'end_time' => '20:00:00',
                    'location' => 'Islamic Center Jakarta',
                    'venue' => 'Main Hall',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => true,
                    'price' => 0,
                    'quota' => 4000,
                    'max_participants' => 4000,
                    'current_participants' => 987,
                    'benefits' => 'Free Entry, Islamic Wedding Guide, Prewedding Hijab Styling Tips, Vendor Promo, Al-Quran Doorprize',
                    'requirements' => 'Registrasi online, Dress code sopan (muslimah disarankan berhijab)',
                    'organizer_name' => 'HASTANA Islamic Wedding',
                    'contact_email' => 'wedding@hastana.id',
                    'contact_phone' => '081234567903',
                    'tags' => json_encode(['wedding', 'expo', 'islamic', 'muslim', 'free-event', 'syariah']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
            ]);
        }

        // ============================================
        // KATEGORI 4: SERTIFIKASI HASTANA (5 events)
        // ============================================
        $sertifikasiCategory = $categories->where('slug', 'sertifikasi-hastana')->first();
        if ($sertifikasiCategory) {
            $allEvents = array_merge($allEvents, [
                [
                    'title' => 'Sertifikasi Wedding Organizer Profesional',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program sertifikasi resmi untuk menjadi Wedding Organizer profesional yang diakui industri.</p><p><strong>Materi Sertifikasi:</strong></p><ul><li>Wedding Industry Overview</li><li>Wedding Planning & Management</li><li>Vendor Coordination</li><li>Budget & Timeline Management</li><li>Problem Solving on Wedding Day</li><li>Marketing & Branding for WO</li><li>Legal & Contract</li></ul><p><strong>Benefit:</strong> Sertifikat resmi HASTANA yang diakui industri pernikahan Indonesia</p>',
                    'short_description' => 'Program sertifikasi resmi Wedding Organizer profesional.',
                    'start_date' => '2025-11-18',
                    'end_date' => '2025-11-22',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA Training Center Jakarta',
                    'venue' => 'Training Room 1',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 5000000,
                    'quota' => 20,
                    'max_participants' => 20,
                    'current_participants' => 12,
                    'benefits' => 'Sertifikat Resmi HASTANA, Modul Lengkap, Lunch & Coffee Break 5 Hari, Ujian Sertifikasi, 3 Bulan Mentoring, Join Alumni Network',
                    'requirements' => 'Minimal SMA/sederajat, Memiliki passion di wedding industry, Membawa laptop',
                    'organizer_name' => 'HASTANA Certification Board',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567904',
                    'tags' => json_encode(['sertifikasi', 'wedding-organizer', 'professional', 'career']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Sertifikasi Event Organizer & MICE Professional',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program sertifikasi untuk Event Organizer dan MICE (Meeting, Incentive, Convention, Exhibition) Professional.</p><p><strong>Kurikulum:</strong></p><ul><li>Event Management Fundamentals</li><li>MICE Industry Standards</li><li>Event Marketing & Sponsorship</li><li>Venue & Logistics Management</li><li>Risk Management</li><li>Post-Event Evaluation</li></ul>',
                    'short_description' => 'Program sertifikasi Event Organizer dan MICE Professional.',
                    'start_date' => '2025-12-02',
                    'end_date' => '2025-12-06',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA Training Center Jakarta',
                    'venue' => 'Training Room 2',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 6000000,
                    'quota' => 20,
                    'max_participants' => 20,
                    'current_participants' => 8,
                    'benefits' => 'Sertifikat HASTANA MICE Professional, Modul & Case Study, Lunch 5 Hari, Field Study ke Event, Ujian Sertifikasi, Lifetime Alumni Support',
                    'requirements' => 'Minimal D3/S1, Pengalaman event minimal 1 tahun (diutamakan), Laptop',
                    'organizer_name' => 'HASTANA Certification Board',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567905',
                    'tags' => json_encode(['sertifikasi', 'event-organizer', 'mice', 'professional']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
                [
                    'title' => 'Sertifikasi Digital Marketing Specialist',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program sertifikasi digital marketing dengan kurikulum terkini dan praktek langsung.</p><p><strong>Materi:</strong></p><ul><li>Digital Marketing Strategy</li><li>SEO & SEM</li><li>Social Media Marketing</li><li>Content Marketing</li><li>Email Marketing</li><li>Analytics & Reporting</li><li>Paid Advertising (Google Ads, Meta Ads)</li></ul><p>Termasuk ujian sertifikasi dan capstone project!</p>',
                    'short_description' => 'Program sertifikasi Digital Marketing Specialist.',
                    'start_date' => '2025-11-11',
                    'end_date' => '2025-11-15',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA Digital Academy',
                    'venue' => 'Lab Digital Marketing',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 4500000,
                    'quota' => 25,
                    'max_participants' => 25,
                    'current_participants' => 18,
                    'benefits' => 'Sertifikat HASTANA Digital Marketing Specialist, Modul Digital, Lunch & Snack, Akses Tools & Template, 2 Bulan Konsultasi, Job Connector',
                    'requirements' => 'Minimal SMA, Familiar dengan internet & social media, Laptop dengan internet',
                    'organizer_name' => 'HASTANA Digital Academy',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567906',
                    'tags' => json_encode(['sertifikasi', 'digital-marketing', 'specialist', 'online-marketing']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
                [
                    'title' => 'Sertifikasi Project Management Professional (PMP Preparation)',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program persiapan sertifikasi Project Management Professional dengan standar internasional.</p><p><strong>Coverage:</strong></p><ul><li>Project Management Framework</li><li>Initiating & Planning</li><li>Executing & Monitoring</li><li>Controlling & Closing</li><li>Agile & Hybrid Approaches</li><li>PMP Exam Simulation</li></ul>',
                    'short_description' => 'Program persiapan sertifikasi Project Management Professional.',
                    'start_date' => '2025-12-09',
                    'end_date' => '2025-12-13',
                    'start_time' => '09:00:00',
                    'end_time' => '18:00:00',
                    'location' => 'HASTANA Professional Institute',
                    'venue' => 'Executive Training Room',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 8000000,
                    'quota' => 15,
                    'max_participants' => 15,
                    'current_participants' => 9,
                    'benefits' => 'Sertifikat HASTANA PMP Preparation, PMBOK Guide, Lunch & Coffee Break, 500+ Practice Questions, Exam Voucher Discount, 6 Bulan Study Group',
                    'requirements' => 'Minimal S1, 3 tahun pengalaman project management, Laptop',
                    'organizer_name' => 'HASTANA Professional Institute',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567907',
                    'tags' => json_encode(['sertifikasi', 'project-management', 'pmp', 'professional']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => true,
                    'is_trending' => false,
                ],
                [
                    'title' => 'Sertifikasi HR Professional & Talent Management',
                    'event_category_id' => $sertifikasiCategory->id,
                    'event_type' => 'internal',
                    'description' => '<p>Program sertifikasi untuk HR Professional dengan fokus pada talent management dan people development.</p><p><strong>Materi:</strong></p><ul><li>Strategic HRM</li><li>Talent Acquisition & Recruitment</li><li>Performance Management</li><li>Learning & Development</li><li>Compensation & Benefits</li><li>Employee Relations</li><li>HR Analytics</li></ul>',
                    'short_description' => 'Program sertifikasi HR Professional dan Talent Management.',
                    'start_date' => '2025-11-25',
                    'end_date' => '2025-11-29',
                    'start_time' => '09:00:00',
                    'end_time' => '17:00:00',
                    'location' => 'HASTANA HR Institute',
                    'venue' => 'Training Hall',
                    'city' => 'Jakarta',
                    'province' => 'DKI Jakarta',
                    'is_free' => false,
                    'price' => 5500000,
                    'quota' => 20,
                    'max_participants' => 20,
                    'current_participants' => 13,
                    'benefits' => 'Sertifikat HASTANA HR Professional, Modul & Template HR, Lunch 5 Hari, HR Tools & Software Trial, Ujian Sertifikasi, HR Community Access',
                    'requirements' => 'Minimal D3, Bekerja di HR atau tertarik karir HR, Laptop',
                    'organizer_name' => 'HASTANA HR Institute',
                    'contact_email' => 'certification@hastana.id',
                    'contact_phone' => '081234567908',
                    'tags' => json_encode(['sertifikasi', 'hr', 'human-resource', 'talent-management']),
                    'status' => 'published',
                    'is_active' => true,
                    'is_featured' => false,
                    'is_trending' => true,
                ],
            ]);
        }

        // Insert semua events
        foreach ($allEvents as $eventData) {
            $eventData['slug'] = Str::slug($eventData['title']);
            EventHastana::create($eventData);
        }

        $this->command->info('✅ Event Hastana seeder berhasil dijalankan!');
        $this->command->info('   📋 Total events created: ' . count($allEvents));
        $this->command->line('');
        $this->command->info('   📊 Breakdown per kategori:');
        
        if ($workshopCategory) {
            $workshopCount = EventHastana::where('event_category_id', $workshopCategory->id)->count();
            $this->command->info("   - {$workshopCategory->name}: {$workshopCount} events");
        }
        if ($seminarCategory) {
            $seminarCount = EventHastana::where('event_category_id', $seminarCategory->id)->count();
            $this->command->info("   - {$seminarCategory->name}: {$seminarCount} events");
        }
        if ($weddingCategory) {
            $weddingCount = EventHastana::where('event_category_id', $weddingCategory->id)->count();
            $this->command->info("   - {$weddingCategory->name}: {$weddingCount} events");
        }
        if ($sertifikasiCategory) {
            $sertifikasiCount = EventHastana::where('event_category_id', $sertifikasiCategory->id)->count();
            $this->command->info("   - {$sertifikasiCategory->name}: {$sertifikasiCount} events");
        }
    }
}
