<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\WeddingOrganizer;
use App\Models\User;
use App\Models\Region;
use Carbon\Carbon;
use Faker\Factory as Faker;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class WeddingOrganizerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');
        
        // Get available users and regions
        $users = User::where('id', '>', 2)->pluck('id')->toArray(); // Skip admin users
        $regions = Region::pluck('id')->toArray();
        
        $weddingOrganizers = [
            // Premium Wedding Organizers
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Elegant Wedding Organizer',
                'slug' => 'elegant-wedding-organizer',
                'brand_name' => 'Elegant Wedding',
                'description' => 'Wedding organizer premium dengan pengalaman lebih dari 10 tahun dalam mengorganisir pernikahan mewah dan eksklusif.',
                'phone' => '+62-21-55667788',
                'email' => 'info@elegantwedding.co.id',
                'website' => 'https://www.elegantwedding.co.id',
                'instagram' => '@elegant_wedding_id',
                'address' => 'Jl. Kemang Raya No. 123, Jakarta Selatan',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '12560',
                'certification_level' => 'expert',
                'established_year' => 2012,
                'business_type' => 'company',
                'business_license' => 'SIUP/123/2012',
                'specializations' => json_encode(['Wedding Luxury', 'Destination Wedding', 'Traditional Wedding']),
                'services' => json_encode(['Full Wedding Planning', 'Wedding Coordination', 'Venue Decoration']),
                'price_range_min' => 50000000,
                'price_range_max' => 200000000,
                'completed_events' => 150,
                'rating' => 4.8,
                'verification_status' => 'verified',
                'is_featured' => true,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(6),
                'legal_entity_type' => 'company',
                'nib_number' => '1234567890123456',
                'npwp_number' => '01.234.567.8-901.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Bali Dream Wedding',
                'slug' => 'bali-dream-wedding',
                'brand_name' => 'Bali Dream',
                'description' => 'Spesialis destination wedding di Bali dengan pemandangan pantai yang memukau dan pelayanan internasional.',
                'phone' => '+62-361-98765432',
                'email' => 'hello@balidreamwedding.com',
                'website' => 'https://www.balidreamwedding.com',
                'instagram' => '@bali_dream_wedding',
                'address' => 'Jl. Sunset Road No. 45, Seminyak, Bali',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'postal_code' => '80361',
                'certification_level' => 'advanced',
                'established_year' => 2015,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/456/2015',
                'specializations' => json_encode(['Beach Wedding', 'Villa Wedding', 'Garden Wedding']),
                'services' => json_encode(['Destination Wedding', 'Photography', 'Catering', 'Decoration']),
                'price_range_min' => 75000000,
                'price_range_max' => 300000000,
                'completed_events' => 89,
                'rating' => 4.9,
                'verification_status' => 'verified',
                'is_featured' => true,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(4),
                'legal_entity_type' => 'partnership',
                'nib_number' => '2345678901234567',
                'npwp_number' => '02.345.678.9-012.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Jogja Traditional Wedding',
                'slug' => 'jogja-traditional-wedding',
                'brand_name' => 'Jogja Traditional',
                'description' => 'Wedding organizer spesialis pernikahan adat Jawa dengan sentuhan modern dan pelestarian budaya tradisional.',
                'phone' => '+62-274-11223344',
                'email' => 'info@jogjatraditional.id',
                'website' => 'https://www.jogjatraditional.id',
                'instagram' => '@jogja_traditional_wedding',
                'address' => 'Jl. Malioboro No. 67, Yogyakarta',
                'city' => 'Yogyakarta',
                'province' => 'D.I. Yogyakarta',
                'postal_code' => '55271',
                'certification_level' => 'intermediate',
                'established_year' => 2018,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/789/2018',
                'specializations' => json_encode(['Javanese Wedding', 'Traditional Ceremony', 'Cultural Wedding']),
                'services' => json_encode(['Traditional Decoration', 'Cultural Consultation', 'Traditional Music']),
                'price_range_min' => 25000000,
                'price_range_max' => 80000000,
                'completed_events' => 45,
                'rating' => 4.6,
                'verification_status' => 'verified',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(2),
                'legal_entity_type' => 'partnership',
                'nib_number' => '3456789012345678',
                'npwp_number' => '03.456.789.0-123.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Surabaya Modern Wedding',
                'slug' => 'surabaya-modern-wedding',
                'brand_name' => 'Surabaya Modern',
                'description' => 'Wedding organizer modern dengan konsep minimalis dan elegant untuk generasi milenial di Surabaya.',
                'phone' => '+62-31-77889900',
                'email' => 'contact@surabayamodern.co.id',
                'website' => 'https://www.surabayamodern.co.id',
                'instagram' => '@surabaya_modern_wedding',
                'address' => 'Jl. HR. Muhammad No. 89, Surabaya',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60115',
                'certification_level' => 'advanced',
                'established_year' => 2019,
                'business_type' => 'company',
                'business_license' => 'SIUP/101/2019',
                'specializations' => json_encode(['Modern Wedding', 'Minimalist Wedding', 'Urban Wedding']),
                'services' => json_encode(['Event Planning', 'Modern Decoration', 'Digital Invitation']),
                'price_range_min' => 30000000,
                'price_range_max' => 120000000,
                'completed_events' => 67,
                'rating' => 4.7,
                'verification_status' => 'verified',
                'is_featured' => true,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonth(),
                'legal_entity_type' => 'company',
                'nib_number' => '4567890123456789',
                'npwp_number' => '04.567.890.1-234.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Medan Grand Wedding',
                'slug' => 'medan-grand-wedding',
                'brand_name' => 'Medan Grand',
                'description' => 'Wedding organizer terpercaya di Medan dengan spesialisasi grand wedding dan acara besar dengan kapasitas hingga 1000 tamu.',
                'phone' => '+62-61-22334455',
                'email' => 'info@medangrand.id',
                'website' => 'https://www.medangrand.id',
                'instagram' => '@medan_grand_wedding',
                'address' => 'Jl. Gatot Subroto No. 234, Medan',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'postal_code' => '20235',
                'certification_level' => 'intermediate',
                'established_year' => 2017,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/202/2017',
                'specializations' => json_encode(['Grand Wedding', 'Large Scale Event', 'Hotel Wedding']),
                'services' => json_encode(['Grand Decoration', 'Sound System', 'Catering Management']),
                'price_range_min' => 40000000,
                'price_range_max' => 150000000,
                'completed_events' => 38,
                'rating' => 4.5,
                'verification_status' => 'verified',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => Carbon::now()->subWeeks(3),
                'legal_entity_type' => 'partnership',
                'nib_number' => '5678901234567890',
                'npwp_number' => '05.678.901.2-345.000',
                'legal_document_status' => 'verified',
            ],
            
            // Emerging Wedding Organizers
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Fresh Start Wedding',
                'slug' => 'fresh-start-wedding',
                'brand_name' => 'Fresh Start',
                'description' => 'Wedding organizer baru dengan ide-ide kreatif dan harga yang terjangkau untuk pasangan muda.',
                'phone' => '+62-22-44556677',
                'email' => 'hello@freshstartwedding.com',
                'website' => 'https://www.freshstartwedding.com',
                'instagram' => '@fresh_start_wedding',
                'address' => 'Jl. Dago No. 123, Bandung',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40135',
                'certification_level' => 'basic',
                'established_year' => 2022,
                'business_type' => 'individual',
                'business_license' => 'SIUP/303/2022',
                'specializations' => json_encode(['Budget Wedding', 'Creative Wedding', 'Outdoor Wedding']),
                'services' => json_encode(['Basic Planning', 'DIY Decoration', 'Budget Consultation']),
                'price_range_min' => 15000000,
                'price_range_max' => 50000000,
                'completed_events' => 12,
                'rating' => 4.3,
                'verification_status' => 'pending',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => null,
                'legal_entity_type' => 'individual',
                'nib_number' => null,
                'npwp_number' => '06.789.012.3-456.000',
                'legal_document_status' => 'pending_review',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Makassar Wedding Planner',
                'slug' => 'makassar-wedding-planner',
                'brand_name' => 'Makassar Wedding',
                'description' => 'Wedding planner profesional di Makassar dengan spesialisasi pernikahan Bugis-Makassar dan modern wedding.',
                'phone' => '+62-411-33445566',
                'email' => 'info@makassarwedding.id',
                'website' => null,
                'instagram' => '@makassar_wedding_planner',
                'address' => 'Jl. Pengayoman No. 45, Makassar',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'postal_code' => '90231',
                'certification_level' => 'basic',
                'established_year' => 2021,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/404/2021',
                'specializations' => json_encode(['Bugis Wedding', 'Modern Wedding', 'Cultural Fusion']),
                'services' => json_encode(['Cultural Ceremony', 'Traditional Decoration', 'Music Arrangement']),
                'price_range_min' => 20000000,
                'price_range_max' => 70000000,
                'completed_events' => 23,
                'rating' => 4.4,
                'verification_status' => 'pending',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => null,
                'legal_entity_type' => 'partnership',
                'nib_number' => '7890123456789012',
                'npwp_number' => '07.890.123.4-567.000',
                'legal_document_status' => 'pending_review',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Palembang Romantic Wedding',
                'slug' => 'palembang-romantic-wedding',
                'brand_name' => 'Palembang Romantic',
                'description' => 'Wedding organizer romantis di Palembang dengan konsep intimate wedding dan pelayanan personal untuk setiap pasangan.',
                'phone' => '+62-711-88776655',
                'email' => 'romantic@palembangwedding.co.id',
                'website' => 'https://www.palembangromantic.id',
                'instagram' => '@palembang_romantic_wedding',
                'address' => 'Jl. Sudirman No. 456, Palembang',
                'city' => 'Palembang',
                'province' => 'Sumatera Selatan',
                'postal_code' => '30126',
                'certification_level' => 'intermediate',
                'established_year' => 2020,
                'business_type' => 'company',
                'business_license' => 'SIUP/505/2020',
                'specializations' => json_encode(['Intimate Wedding', 'Romantic Wedding', 'Garden Party']),
                'services' => json_encode(['Romantic Decoration', 'Intimate Planning', 'Photography Package']),
                'price_range_min' => 28000000,
                'price_range_max' => 90000000,
                'completed_events' => 34,
                'rating' => 4.6,
                'verification_status' => 'verified',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(3),
                'legal_entity_type' => 'company',
                'nib_number' => '8901234567890123',
                'npwp_number' => '08.901.234.5-678.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Semarang Elegant Celebration',
                'slug' => 'semarang-elegant-celebration',
                'brand_name' => 'Semarang Elegant',
                'description' => 'Wedding organizer eksklusif di Semarang dengan spesialisasi acara mewah dan dekorasi berkelas internasional.',
                'phone' => '+62-24-99887766',
                'email' => 'elegant@semarangcelebration.id',
                'website' => 'https://www.semarangelegant.co.id',
                'instagram' => '@semarang_elegant_celebration',
                'address' => 'Jl. Pemuda No. 789, Semarang',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50132',
                'certification_level' => 'expert',
                'established_year' => 2014,
                'business_type' => 'company',
                'business_license' => 'SIUP/606/2014',
                'specializations' => json_encode(['Luxury Wedding', 'International Style', 'Hotel Wedding']),
                'services' => json_encode(['Luxury Planning', 'International Decoration', 'VIP Service']),
                'price_range_min' => 60000000,
                'price_range_max' => 250000000,
                'completed_events' => 98,
                'rating' => 4.9,
                'verification_status' => 'verified',
                'is_featured' => true,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(8),
                'legal_entity_type' => 'company',
                'nib_number' => '9012345678901234',
                'npwp_number' => '09.012.345.6-789.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Lampung Natural Wedding',
                'slug' => 'lampung-natural-wedding',
                'brand_name' => 'Lampung Natural',
                'description' => 'Wedding organizer dengan konsep natural dan eco-friendly, menghadirkan pernikahan yang harmonis dengan alam.',
                'phone' => '+62-721-55443322',
                'email' => 'natural@lampungwedding.id',
                'website' => 'https://www.lampungnatural.co.id',
                'instagram' => '@lampung_natural_wedding',
                'address' => 'Jl. Zainal Abidin No. 321, Bandar Lampung',
                'city' => 'Bandar Lampung',
                'province' => 'Lampung',
                'postal_code' => '35142',
                'certification_level' => 'intermediate',
                'established_year' => 2019,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/707/2019',
                'specializations' => json_encode(['Natural Wedding', 'Eco-friendly Wedding', 'Outdoor Ceremony']),
                'services' => json_encode(['Natural Decoration', 'Outdoor Planning', 'Sustainable Catering']),
                'price_range_min' => 22000000,
                'price_range_max' => 75000000,
                'completed_events' => 41,
                'rating' => 4.5,
                'verification_status' => 'verified',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(5),
                'legal_entity_type' => 'partnership',
                'nib_number' => '0123456789012345',
                'npwp_number' => '10.123.456.7-890.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Bogor Highland Wedding',
                'slug' => 'bogor-highland-wedding',
                'brand_name' => 'Bogor Highland',
                'description' => 'Spesialis destination wedding di daerah pegunungan Bogor dengan nuansa sejuk dan pemandangan alam yang menakjubkan.',
                'phone' => '+62-251-77665544',
                'email' => 'highland@bogorwedding.co.id',
                'website' => 'https://www.bogohighland.id',
                'instagram' => '@bogor_highland_wedding',
                'address' => 'Jl. Raya Puncak No. 567, Bogor',
                'city' => 'Bogor',
                'province' => 'Jawa Barat',
                'postal_code' => '16750',
                'certification_level' => 'advanced',
                'established_year' => 2016,
                'business_type' => 'company',
                'business_license' => 'SIUP/808/2016',
                'specializations' => json_encode(['Mountain Wedding', 'Destination Wedding', 'Highland Ceremony']),
                'services' => json_encode(['Mountain Venue', 'Highland Decoration', 'Nature Photography']),
                'price_range_min' => 45000000,
                'price_range_max' => 180000000,
                'completed_events' => 73,
                'rating' => 4.8,
                'verification_status' => 'verified',
                'is_featured' => true,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(7),
                'legal_entity_type' => 'company',
                'nib_number' => '1234567890123457',
                'npwp_number' => '11.234.567.8-901.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Tangerang Creative Wedding',
                'slug' => 'tangerang-creative-wedding',
                'brand_name' => 'Tangerang Creative',
                'description' => 'Wedding organizer inovatif di Tangerang dengan konsep kreatif dan teknologi terkini untuk generasi digital native.',
                'phone' => '+62-21-33221100',
                'email' => 'creative@tangerangwedding.id',
                'website' => 'https://www.tangerangcreative.co.id',
                'instagram' => '@tangerang_creative_wedding',
                'address' => 'Jl. BSD Raya No. 888, Tangerang Selatan',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'postal_code' => '15310',
                'certification_level' => 'advanced',
                'established_year' => 2021,
                'business_type' => 'company',
                'business_license' => 'SIUP/909/2021',
                'specializations' => json_encode(['Creative Wedding', 'Tech Wedding', 'Digital Innovation']),
                'services' => json_encode(['Digital Planning', 'Tech Integration', 'Creative Concept']),
                'price_range_min' => 35000000,
                'price_range_max' => 140000000,
                'completed_events' => 29,
                'rating' => 4.7,
                'verification_status' => 'verified',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(2),
                'legal_entity_type' => 'company',
                'nib_number' => '2345678901234568',
                'npwp_number' => '12.345.678.9-012.000',
                'legal_document_status' => 'verified',
            ],
        ];

        foreach ($weddingOrganizers as $organizer) {
            WeddingOrganizer::updateOrCreate(
                ['organizer_name' => $organizer['organizer_name']],
                $organizer
            );
        }

        // Additional data from provided list (Sumsel & Lampung)
        $regionAliasMap = [
            'Sumsel' => 'Sumatera Selatan',
            'Lampung' => 'Lampung',
        ];

        $sheetOrganizers = [
            ['no_anggota' => 'HI.07.002', 'organizer_name' => 'Dhiary Wedding Organizer', 'email' => 'dhiary.wo@gmail.com', 'name' => 'M Fritran Garida', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.003', 'organizer_name' => 'Makna Wedding & Event Planner', 'email' => 'ramadhona.utama@gmail.com', 'name' => 'Rama Dhona Utama', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.004', 'organizer_name' => 'Sarana Wedding Planner & Organizer', 'email' => 'shesagroup@gmail.com', 'name' => 'Sheilla Andriani Rizky', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.005', 'organizer_name' => 'Keluarga Baba', 'email' => 'emailkeluargababa@gmail.com', 'name' => 'Husni Wirya Kusuma', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.006', 'organizer_name' => 'Filfin wedding organizer', 'email' => 'filfinweddingorganizer@gmail.com', 'name' => 'M. Abdhu', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.007', 'organizer_name' => 'Cattleya Wedding Planner & Organizer', 'email' => 'cattleyaorganizer@gmail.com', 'name' => 'Medi ardiansyah', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.008', 'organizer_name' => 'Project Manten WO', 'email' => 'dwi.cahyoyunagara@gmail.com', 'name' => 'Dwi Cahyo Nugraha', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.009', 'organizer_name' => 'Jefri Wedding Planner & Organizer', 'email' => 'Jefriweddingorganizer@gmail.com', 'name' => 'Jefri Ahmad Hafiz', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.012', 'organizer_name' => 'L6 Wo', 'email' => 'Elnam.wo@gmail.com', 'name' => 'Iqbal Caesar Ichsan, SE', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.013', 'organizer_name' => '3D WEDDING ORGANIZER', 'email' => 'deptroduction13@gmail.com', 'name' => 'Dina Septianah', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.015', 'organizer_name' => 'Bidadari Syurga', 'email' => 'eo.bidadarisyurga@gmail.com', 'name' => 'Wahyu Abdi Harianto', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.017', 'organizer_name' => 'Dinar Wedding Organizer', 'email' => 'dinarweddingorganizer@gmail.com', 'name' => 'Ade Apriyanto', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.018', 'organizer_name' => 'Putra Sakti WO', 'email' => 'ahmadokiputrasakti@gmail.com', 'name' => 'Ahmadokiputrasakti@gmail.com', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.019', 'organizer_name' => 'DK Wedding Organizer', 'email' => 'deddykurniawan.w@gmail.com', 'name' => 'Kgs. Choirul Dedi Kurniawan', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.020', 'organizer_name' => "Temen manten wedding organizer syar'i", 'email' => 'igunbagus@gmail.com', 'name' => 'Igun bagus saputra', 'region_name' => 'Sumsel'],
            ['no_anggota' => 'HI.07.021', 'organizer_name' => 'Getmerits', 'email' => 'ifnialfionita@gmail.com', 'name' => 'Ifni Alfionita', 'region_name' => 'Sumsel'],

            ['no_anggota' => 'HI.06.001', 'organizer_name' => 'Muli Mekhnai Production', 'email' => 'mulimekhnaiproduction@gmail.com', 'name' => 'Ruland Rachmat Mantiri', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.003', 'organizer_name' => 'SABILA PROJECT WO', 'email' => 'weddingsabila@gmail.com', 'name' => 'RIZKY SABILA AZHARI', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.005', 'organizer_name' => 'Dream Event Planner', 'email' => 'yunainivesi@gmail.com', 'name' => 'Yesi Yuniain', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.007', 'organizer_name' => "Bell's Organizer", 'email' => 'bells.organizer95@gmail.com', 'name' => 'Elyus Setiawan', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.009', 'organizer_name' => 'Gading Planner', 'email' => 'gadingplanner@gmail.com', 'name' => 'Oktavia Pancarani', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.010', 'organizer_name' => 'Samara Production', 'email' => 'gustianalfarzi1608@gmail.com', 'name' => 'Muhammad Gustian Alfarizi', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.012', 'organizer_name' => 'Ivan N Friends (belum isi gform)', 'email' => null, 'name' => '0', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.014', 'organizer_name' => 'Audrey Production', 'email' => 'hardykurniawan@gmail.com', 'name' => 'Hardi Kurniawan', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.016', 'organizer_name' => 'Helio official', 'email' => 'wiwinwidiatwo@gmail.com', 'name' => 'Wiwin widiawati', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.017', 'organizer_name' => 'Inscribe Organizer', 'email' => 'inscribe.organizer@gmail.com', 'name' => 'Viola Natalia Budiman', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.018', 'organizer_name' => 'WiBi PRO ORGANIZER', 'email' => 'wibipro@gmail.com', 'name' => 'Benny Fernando', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.021', 'organizer_name' => 'Malikastory Wedding Planner', 'email' => 'malika.weddingplanner@gmail.com', 'name' => 'Lisa Novita Z', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.006', 'organizer_name' => 'CENDANA PRODUCTION', 'email' => 'pebigitbasari@gmail.com', 'name' => 'Pebiti Gita Sari', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.022', 'organizer_name' => 'Abieproduction Wo & Planner', 'email' => 'abieproduction9@gmail.com', 'name' => 'Fhatur Rohman', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.023', 'organizer_name' => 'TY Wedding Organizer', 'email' => 'afrianromaldi@gmail.com', 'name' => 'Afrina romaldini s', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.024', 'organizer_name' => 'Jejakmoo.id', 'email' => 'egasasel@gmail.com', 'name' => 'Ega sasa remanda', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.025', 'organizer_name' => 'AKL Organizer (belum isi gform)', 'email' => null, 'name' => '0', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.026', 'organizer_name' => 'Sahas Production', 'email' => 'sahasproduction70@gmail.com', 'name' => 'Rizki ardiayanto', 'region_name' => 'Lampung'],
            ['no_anggota' => 'HI.06.027', 'organizer_name' => 'Shine Organizer (belum isi gform)', 'email' => null, 'name' => '0', 'region_name' => 'Lampung'],
        ];

        foreach ($sheetOrganizers as $row) {
            $mappedRegion = $regionAliasMap[$row['region_name']] ?? $row['region_name'];
            $region = Region::where('region_name', $mappedRegion)->first();
            $regionId = $region ? $region->id : ($regions[0] ?? null);

            $hasValidUser = !empty($row['email']) && !empty($row['name']) && $row['name'] !== '0';
            if ($hasValidUser) {
                $user = User::updateOrCreate(
                    ['email' => strtolower($row['email'])],
                    [
                        'name' => $row['name'],
                        'password' => Hash::make('password123'),
                        'role' => 'member',
                        'status' => 'active',
                        'email_verified_at' => Carbon::now(),
                        'no_anggota' => $row['no_anggota'],
                    ]
                );
            } else {
                $placeholderEmail = 'member+' . Str::slug($row['no_anggota']) . '@hastana.local';
                $user = User::updateOrCreate(
                    ['email' => $placeholderEmail],
                    [
                        'name' => ($row['name'] && $row['name'] !== '0') ? $row['name'] : $row['organizer_name'],
                        'password' => Hash::make('password123'),
                        'role' => 'member',
                        'status' => 'active',
                        'email_verified_at' => Carbon::now(),
                        'no_anggota' => $row['no_anggota'],
                    ]
                );
            }
            $userId = $user->id;

            $slugBase = Str::slug($row['organizer_name']);
            $slug = $slugBase;
            // ensure unique slug by appending membership code if exists conflict
            if (WeddingOrganizer::where('slug', $slug)->exists()) {
                $slug .= '-' . Str::slug($row['no_anggota']);
            }

            WeddingOrganizer::updateOrCreate(
                ['organizer_name' => $row['organizer_name']],
                [
                    'user_id' => $userId,
                    'region_id' => $regionId,
                    'organizer_name' => $row['organizer_name'],
                    'slug' => $slug,
                    'brand_name' => $row['organizer_name'],
                    'email' => $row['email'],
                    'status' => 'active',
                    'verification_status' => 'verified',
                ]
            );
        }

        $this->command->info('WeddingOrganizer seeder completed! Created ' . count($weddingOrganizers) . ' wedding organizers with diverse profiles.');
    }
}
