<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\WeddingOrganizer;
use App\Models\User;
use App\Models\Region;
use Carbon\Carbon;
use Faker\Factory as Faker;

class WeddingOrganizerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');
        
        // Get available users and regions
        $users = User::where('id', '>', 2)->pluck('id')->toArray(); // Skip admin users
        $regions = Region::pluck('id')->toArray();
        
        $weddingOrganizers = [
            // Premium Wedding Organizers
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Elegant Wedding Organizer',
                'slug' => 'elegant-wedding-organizer',
                'brand_name' => 'Elegant Wedding',
                'description' => 'Wedding organizer premium dengan pengalaman lebih dari 10 tahun dalam mengorganisir pernikahan mewah dan eksklusif.',
                'phone' => '+62-21-55667788',
                'email' => 'info@elegantwedding.co.id',
                'website' => 'https://www.elegantwedding.co.id',
                'instagram' => '@elegant_wedding_id',
                'address' => 'Jl. Kemang Raya No. 123, Jakarta Selatan',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '12560',
                'certification_level' => 'expert',
                'established_year' => 2012,
                'business_type' => 'company',
                'business_license' => 'SIUP/123/2012',
                'specializations' => json_encode(['Wedding Luxury', 'Destination Wedding', 'Traditional Wedding']),
                'services' => json_encode(['Full Wedding Planning', 'Wedding Coordination', 'Venue Decoration']),
                'price_range_min' => 50000000,
                'price_range_max' => 200000000,
                'completed_events' => 150,
                'rating' => 4.8,
                'verification_status' => 'verified',
                'is_featured' => true,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(6),
                'legal_entity_type' => 'company',
                'nib_number' => '1234567890123456',
                'npwp_number' => '01.234.567.8-901.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Bali Dream Wedding',
                'slug' => 'bali-dream-wedding',
                'brand_name' => 'Bali Dream',
                'description' => 'Spesialis destination wedding di Bali dengan pemandangan pantai yang memukau dan pelayanan internasional.',
                'phone' => '+62-361-98765432',
                'email' => 'hello@balidreamwedding.com',
                'website' => 'https://www.balidreamwedding.com',
                'instagram' => '@bali_dream_wedding',
                'address' => 'Jl. Sunset Road No. 45, Seminyak, Bali',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'postal_code' => '80361',
                'certification_level' => 'advanced',
                'established_year' => 2015,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/456/2015',
                'specializations' => json_encode(['Beach Wedding', 'Villa Wedding', 'Garden Wedding']),
                'services' => json_encode(['Destination Wedding', 'Photography', 'Catering', 'Decoration']),
                'price_range_min' => 75000000,
                'price_range_max' => 300000000,
                'completed_events' => 89,
                'rating' => 4.9,
                'verification_status' => 'verified',
                'is_featured' => true,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(4),
                'legal_entity_type' => 'partnership',
                'nib_number' => '2345678901234567',
                'npwp_number' => '02.345.678.9-012.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Jogja Traditional Wedding',
                'slug' => 'jogja-traditional-wedding',
                'brand_name' => 'Jogja Traditional',
                'description' => 'Wedding organizer spesialis pernikahan adat Jawa dengan sentuhan modern dan pelestarian budaya tradisional.',
                'phone' => '+62-274-11223344',
                'email' => 'info@jogjatraditional.id',
                'website' => 'https://www.jogjatraditional.id',
                'instagram' => '@jogja_traditional_wedding',
                'address' => 'Jl. Malioboro No. 67, Yogyakarta',
                'city' => 'Yogyakarta',
                'province' => 'D.I. Yogyakarta',
                'postal_code' => '55271',
                'certification_level' => 'intermediate',
                'established_year' => 2018,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/789/2018',
                'specializations' => json_encode(['Javanese Wedding', 'Traditional Ceremony', 'Cultural Wedding']),
                'services' => json_encode(['Traditional Decoration', 'Cultural Consultation', 'Traditional Music']),
                'price_range_min' => 25000000,
                'price_range_max' => 80000000,
                'completed_events' => 45,
                'rating' => 4.6,
                'verification_status' => 'verified',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonths(2),
                'legal_entity_type' => 'partnership',
                'nib_number' => '3456789012345678',
                'npwp_number' => '03.456.789.0-123.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Surabaya Modern Wedding',
                'slug' => 'surabaya-modern-wedding',
                'brand_name' => 'Surabaya Modern',
                'description' => 'Wedding organizer modern dengan konsep minimalis dan elegant untuk generasi milenial di Surabaya.',
                'phone' => '+62-31-77889900',
                'email' => 'contact@surabayamodern.co.id',
                'website' => 'https://www.surabayamodern.co.id',
                'instagram' => '@surabaya_modern_wedding',
                'address' => 'Jl. HR. Muhammad No. 89, Surabaya',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60115',
                'certification_level' => 'advanced',
                'established_year' => 2019,
                'business_type' => 'company',
                'business_license' => 'SIUP/101/2019',
                'specializations' => json_encode(['Modern Wedding', 'Minimalist Wedding', 'Urban Wedding']),
                'services' => json_encode(['Event Planning', 'Modern Decoration', 'Digital Invitation']),
                'price_range_min' => 30000000,
                'price_range_max' => 120000000,
                'completed_events' => 67,
                'rating' => 4.7,
                'verification_status' => 'verified',
                'is_featured' => true,
                'status' => 'active',
                'verified_at' => Carbon::now()->subMonth(),
                'legal_entity_type' => 'company',
                'nib_number' => '4567890123456789',
                'npwp_number' => '04.567.890.1-234.000',
                'legal_document_status' => 'verified',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Medan Grand Wedding',
                'slug' => 'medan-grand-wedding',
                'brand_name' => 'Medan Grand',
                'description' => 'Wedding organizer terpercaya di Medan dengan spesialisasi grand wedding dan acara besar dengan kapasitas hingga 1000 tamu.',
                'phone' => '+62-61-22334455',
                'email' => 'info@medangrand.id',
                'website' => 'https://www.medangrand.id',
                'instagram' => '@medan_grand_wedding',
                'address' => 'Jl. Gatot Subroto No. 234, Medan',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'postal_code' => '20235',
                'certification_level' => 'intermediate',
                'established_year' => 2017,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/202/2017',
                'specializations' => json_encode(['Grand Wedding', 'Large Scale Event', 'Hotel Wedding']),
                'services' => json_encode(['Grand Decoration', 'Sound System', 'Catering Management']),
                'price_range_min' => 40000000,
                'price_range_max' => 150000000,
                'completed_events' => 38,
                'rating' => 4.5,
                'verification_status' => 'verified',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => Carbon::now()->subWeeks(3),
                'legal_entity_type' => 'partnership',
                'nib_number' => '5678901234567890',
                'npwp_number' => '05.678.901.2-345.000',
                'legal_document_status' => 'verified',
            ],
            
            // Emerging Wedding Organizers
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Fresh Start Wedding',
                'slug' => 'fresh-start-wedding',
                'brand_name' => 'Fresh Start',
                'description' => 'Wedding organizer baru dengan ide-ide kreatif dan harga yang terjangkau untuk pasangan muda.',
                'phone' => '+62-22-44556677',
                'email' => 'hello@freshstartwedding.com',
                'website' => 'https://www.freshstartwedding.com',
                'instagram' => '@fresh_start_wedding',
                'address' => 'Jl. Dago No. 123, Bandung',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40135',
                'certification_level' => 'basic',
                'established_year' => 2022,
                'business_type' => 'individual',
                'business_license' => 'SIUP/303/2022',
                'specializations' => json_encode(['Budget Wedding', 'Creative Wedding', 'Outdoor Wedding']),
                'services' => json_encode(['Basic Planning', 'DIY Decoration', 'Budget Consultation']),
                'price_range_min' => 15000000,
                'price_range_max' => 50000000,
                'completed_events' => 12,
                'rating' => 4.3,
                'verification_status' => 'pending',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => null,
                'legal_entity_type' => 'individual',
                'nib_number' => null,
                'npwp_number' => '06.789.012.3-456.000',
                'legal_document_status' => 'pending_review',
            ],
            [
                'user_id' => $faker->randomElement($users),
                'region_id' => $faker->randomElement($regions),
                'organizer_name' => 'Makassar Wedding Planner',
                'slug' => 'makassar-wedding-planner',
                'brand_name' => 'Makassar Wedding',
                'description' => 'Wedding planner profesional di Makassar dengan spesialisasi pernikahan Bugis-Makassar dan modern wedding.',
                'phone' => '+62-411-33445566',
                'email' => 'info@makassarwedding.id',
                'website' => null,
                'instagram' => '@makassar_wedding_planner',
                'address' => 'Jl. Pengayoman No. 45, Makassar',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'postal_code' => '90231',
                'certification_level' => 'basic',
                'established_year' => 2021,
                'business_type' => 'partnership',
                'business_license' => 'SIUP/404/2021',
                'specializations' => json_encode(['Bugis Wedding', 'Modern Wedding', 'Cultural Fusion']),
                'services' => json_encode(['Cultural Ceremony', 'Traditional Decoration', 'Music Arrangement']),
                'price_range_min' => 20000000,
                'price_range_max' => 70000000,
                'completed_events' => 23,
                'rating' => 4.4,
                'verification_status' => 'pending',
                'is_featured' => false,
                'status' => 'active',
                'verified_at' => null,
                'legal_entity_type' => 'partnership',
                'nib_number' => '7890123456789012',
                'npwp_number' => '07.890.123.4-567.000',
                'legal_document_status' => 'pending_review',
            ],
        ];

        foreach ($weddingOrganizers as $organizer) {
            WeddingOrganizer::updateOrCreate(
                ['organizer_name' => $organizer['organizer_name']],
                $organizer
            );
        }

        $this->command->info('WeddingOrganizer seeder completed! Created ' . count($weddingOrganizers) . ' wedding organizers with diverse profiles.');
    }
}
